-- =============================================================================
-- SALingo — Vocabulary Engine v2: schema expansion + content pool.
-- Additive migration: run in the Supabase SQL Editor, after vocabulary.sql
-- and vocabulary-b2-c1-c2.sql. Safe to re-run (ON CONFLICT DO NOTHING;
-- ALTER ... ADD COLUMN IF NOT EXISTS).
--
-- Adds lexical-knowledge columns (definition, multiple examples, synonyms,
-- antonyms, collocations, register, topic, word-family links, polysemy
-- sense, common mistake) so a word is taught as WORD + MEANING + CONTEXT +
-- COLLOCATION + REGISTER + NUANCE, not just word -> translation (see
-- DEVELOPMENT_REPORT.md § Vocabulary Engine).
-- =============================================================================

alter table public.vocabulary_words add column if not exists part_of_speech text;
alter table public.vocabulary_words add column if not exists definition text;
alter table public.vocabulary_words add column if not exists examples text[];
alter table public.vocabulary_words add column if not exists synonyms text[];
alter table public.vocabulary_words add column if not exists antonyms text[];
alter table public.vocabulary_words add column if not exists collocations text[];
alter table public.vocabulary_words add column if not exists register text check (register in ('casual', 'neutral', 'formal'));
alter table public.vocabulary_words add column if not exists topic text;
alter table public.vocabulary_words add column if not exists related_words text[];
alter table public.vocabulary_words add column if not exists sense text;
alter table public.vocabulary_words add column if not exists common_mistake text;

create index if not exists vocabulary_words_topic_idx on public.vocabulary_words (topic);

-- -----------------------------------------------------------------------------
-- A1 — everyday basics not yet covered: greetings, numbers, colors, clothes,
-- time, basic verbs/adjectives, places, transportation, routines.
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, register, topic)
values
  ('en-vocab-v2-hello', 'en', 'Hello', 'Hola', '/həˈloʊ/', 'Hello, how are you?', 'Daily Life', 'A1', 'interjection', 'A greeting used when meeting someone.', ARRAY['Hello, how are you?', 'She said hello to her neighbor.', 'Hello! Is anyone home?'], 'neutral', 'Greetings'),
  ('en-vocab-v2-goodbye', 'en', 'Goodbye', 'Adiós', '/ɡʊdˈbaɪ/', 'We waved and said goodbye.', 'Daily Life', 'A1', 'interjection', 'A word said when leaving or ending a conversation.', ARRAY['We waved and said goodbye.', 'He said goodbye before boarding the train.', 'Goodbye! See you tomorrow.'], 'neutral', 'Greetings'),
  ('en-vocab-v2-please', 'en', 'Please', 'Por favor', '/pliːz/', 'Please close the door.', 'Daily Life', 'A1', 'adverb', 'Used to make a request more polite.', ARRAY['Please close the door.', 'Can I have some water, please?', 'Please wait a moment.'], 'formal', 'Greetings'),
  ('en-vocab-v2-mother', 'en', 'Mother', 'Madre', '/ˈmʌð.ɚ/', 'My mother works at a hospital.', 'Family', 'A1', 'noun', 'A female parent.', ARRAY['My mother works at a hospital.', 'She looks like her mother.', 'His mother called him twice today.'], 'neutral', 'Family'),
  ('en-vocab-v2-father', 'en', 'Father', 'Padre', '/ˈfɑː.ðɚ/', 'His father is a teacher.', 'Family', 'A1', 'noun', 'A male parent.', ARRAY['His father is a teacher.', 'I asked my father for advice.', 'Their father picks them up from school.'], 'neutral', 'Family'),
  ('en-vocab-v2-one', 'en', 'One', 'Uno', '/wʌn/', 'I have one brother.', 'Daily Life', 'A1', 'number', 'The number 1.', ARRAY['I have one brother.', 'Give me one minute.', 'There is only one seat left.'], 'neutral', 'Numbers'),
  ('en-vocab-v2-ten', 'en', 'Ten', 'Diez', '/ten/', 'The store closes at ten.', 'Daily Life', 'A1', 'number', 'The number 10.', ARRAY['The store closes at ten.', 'We waited for ten minutes.', 'She scored ten out of ten.'], 'neutral', 'Numbers'),
  ('en-vocab-v2-red', 'en', 'Red', 'Rojo', '/red/', 'She bought a red dress.', 'Daily Life', 'A1', 'adjective', 'The color of blood or a ripe tomato.', ARRAY['She bought a red dress.', 'The light turned red.', 'His face went red with embarrassment.'], 'neutral', 'Colors'),
  ('en-vocab-v2-blue', 'en', 'Blue', 'Azul', '/bluː/', 'The sky is blue today.', 'Daily Life', 'A1', 'adjective', 'The color of a clear sky.', ARRAY['The sky is blue today.', 'He wore a blue shirt.', 'They painted the room blue.'], 'neutral', 'Colors'),
  ('en-vocab-v2-shirt', 'en', 'Shirt', 'Camisa', '/ʃɝːt/', 'He ironed his shirt before work.', 'Daily Life', 'A1', 'noun', 'A piece of clothing worn on the upper body.', ARRAY['He ironed his shirt before work.', 'I need a new shirt for the interview.', 'Her shirt was covered in paint.'], 'neutral', 'Clothes'),
  ('en-vocab-v2-shoes', 'en', 'Shoes', 'Zapatos', '/ʃuːz/', 'Take off your shoes at the door.', 'Daily Life', 'A1', 'noun', 'Footwear worn to protect and cover the feet.', ARRAY['Take off your shoes at the door.', 'These shoes are very comfortable.', 'She bought new shoes for the trip.'], 'neutral', 'Clothes'),
  ('en-vocab-v2-monday', 'en', 'Monday', 'Lunes', '/ˈmʌn.deɪ/', 'The meeting is on Monday.', 'Work', 'A1', 'noun', 'The first day of the working week.', ARRAY['The meeting is on Monday.', 'I start my new job on Monday.', 'We always clean the house on Monday.'], 'neutral', 'Days'),
  ('en-vocab-v2-january', 'en', 'January', 'Enero', '/ˈdʒæn.ju.er.i/', 'She was born in January.', 'Daily Life', 'A1', 'noun', 'The first month of the year.', ARRAY['She was born in January.', 'We usually travel in January.', 'The sale starts in January.'], 'neutral', 'Months'),
  ('en-vocab-v2-clock', 'en', 'Clock', 'Reloj', '/klɑːk/', 'The clock on the wall stopped.', 'Daily Life', 'A1', 'noun', 'A device that shows the time.', ARRAY['The clock on the wall stopped.', 'I set the clock to seven.', 'The kitchen clock is always slow.'], 'neutral', 'Time'),
  ('en-vocab-v2-go', 'en', 'Go', 'Ir', '/ɡoʊ/', 'I go to work by bus.', 'Daily Life', 'A1', 'verb', 'To move or travel to a place.', ARRAY['I go to work by bus.', 'We go to the gym on Tuesdays.', 'She goes to school every morning.'], 'neutral', 'Basic Verbs'),
  ('en-vocab-v2-eat', 'en', 'Eat', 'Comer', '/iːt/', 'We eat dinner at eight.', 'Food', 'A1', 'verb', 'To put food in your mouth and swallow it.', ARRAY['We eat dinner at eight.', 'She eats breakfast quickly.', 'Did you eat lunch already?'], 'neutral', 'Basic Verbs'),
  ('en-vocab-v2-happy', 'en', 'Happy', 'Feliz', '/ˈhæp.i/', 'She looked happy at the party.', 'Daily Life', 'A1', 'adjective', 'Feeling or showing pleasure.', ARRAY['She looked happy at the party.', 'I''m happy with my new job.', 'They were happy to see their friends.'], 'neutral', 'Basic Adjectives'),
  ('en-vocab-v2-tired', 'en', 'Tired', 'Cansado/a', '/taɪɚd/', 'He felt tired after the trip.', 'Health', 'A1', 'adjective', 'Needing rest or sleep.', ARRAY['He felt tired after the trip.', 'I''m too tired to cook tonight.', 'The children were tired after school.'], 'neutral', 'Basic Adjectives'),
  ('en-vocab-v2-park', 'en', 'Park', 'Parque', '/pɑːrk/', 'We walked in the park.', 'Daily Life', 'A1', 'noun', 'A public area with grass and trees for recreation.', ARRAY['We walked in the park.', 'The kids play in the park after school.', 'There''s a park near my house.'], 'neutral', 'Places'),
  ('en-vocab-v2-bus', 'en', 'Bus', 'Autobús', '/bʌs/', 'I take the bus to work.', 'Travel', 'A1', 'noun', 'A large road vehicle that carries passengers.', ARRAY['I take the bus to work.', 'The bus was late today.', 'We missed the last bus home.'], 'neutral', 'Transportation'),
  ('en-vocab-v2-wake-up', 'en', 'Wake up', 'Despertarse', '/weɪk ʌp/', 'I wake up at six every day.', 'Daily Life', 'A1', 'phrasal verb', 'To stop sleeping.', ARRAY['I wake up at six every day.', 'She woke up late this morning.', 'The noise woke him up.'], 'neutral', 'Daily Routines')
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- A2 — shopping, travel, health, hobbies, work, education, relationships,
-- weather, technology, city, phrasal verbs.
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, synonyms, register, topic)
values
  ('en-vocab-v2-receipt', 'en', 'Receipt', 'Recibo', '/rɪˈsiːt/', 'Keep the receipt in case you need a refund.', 'Shopping', 'A2', 'noun', 'A printed proof of purchase.', ARRAY['Keep the receipt in case you need a refund.', 'She lost her receipt at the mall.', 'Can I get a receipt, please?'], NULL, 'neutral', 'Shopping'),
  ('en-vocab-v2-discount', 'en', 'Discount', 'Descuento', '/ˈdɪs.kaʊnt/', 'We got a 20% discount on shoes.', 'Shopping', 'A2', 'noun', 'A reduction in the usual price.', ARRAY['We got a 20% discount on shoes.', 'Students receive a discount here.', 'The discount only applies today.'], ARRAY['deal', 'markdown'], 'neutral', 'Shopping'),
  ('en-vocab-v2-try-on', 'en', 'Try on', 'Probarse (ropa)', '/traɪ ɒn/', 'Can I try on this jacket?', 'Shopping', 'A2', 'phrasal verb', 'To put on clothing to see if it fits.', ARRAY['Can I try on this jacket?', 'She tried on three pairs of jeans.', 'Try it on before you buy it.'], NULL, 'neutral', 'Shopping'),
  ('en-vocab-v2-book-flight', 'en', 'Book (a flight)', 'Reservar (un vuelo)', '/bʊk/', 'I booked a flight to Lima.', 'Travel', 'A2', 'verb', 'To arrange to have a seat, room, or service in advance.', ARRAY['I booked a flight to Lima.', 'We booked our hotel online.', 'Have you booked the tickets yet?'], ARRAY['reserve'], 'neutral', 'Travel'),
  ('en-vocab-v2-delay', 'en', 'Delay', 'Retraso', '/dɪˈleɪ/', 'The flight had a two-hour delay.', 'Travel', 'A2', 'noun', 'A period of waiting caused by something happening later than planned.', ARRAY['The flight had a two-hour delay.', 'We apologize for the delay.', 'Traffic caused a long delay.'], NULL, 'neutral', 'Travel'),
  ('en-vocab-v2-fever', 'en', 'Fever', 'Fiebre', '/ˈfiː.vɚ/', 'She has a fever and a cough.', 'Health', 'A2', 'noun', 'A body temperature higher than normal, usually from illness.', ARRAY['She has a fever and a cough.', 'His fever went down after the medicine.', 'A high fever needs a doctor.'], NULL, 'neutral', 'Health'),
  ('en-vocab-v2-hobby', 'en', 'Hobby', 'Pasatiempo', '/ˈhɑː.bi/', 'Painting is my favorite hobby.', 'Daily Life', 'A2', 'noun', 'An activity done regularly for pleasure.', ARRAY['Painting is my favorite hobby.', 'What''s your hobby outside of work?', 'Photography became a serious hobby for him.'], NULL, 'neutral', 'Hobbies'),
  ('en-vocab-v2-shift', 'en', 'Shift', 'Turno', '/ʃɪft/', 'I work the night shift on weekends.', 'Work', 'A2', 'noun', 'A scheduled period of work.', ARRAY['I work the night shift on weekends.', 'Can you cover my shift tomorrow?', 'Her shift starts at 9 AM.'], NULL, 'neutral', 'Work'),
  ('en-vocab-v2-classmate', 'en', 'Classmate', 'Compañero/a de clase', '/ˈklæs.meɪt/', 'She studies with a classmate every week.', 'Education', 'A2', 'noun', 'A person in the same class as you.', ARRAY['She studies with a classmate every week.', 'My classmate helped me with the homework.', 'We used to be classmates in high school.'], NULL, 'neutral', 'Education'),
  ('en-vocab-v2-get-along-with', 'en', 'Get along with', 'Llevarse bien con', '/ɡet əˈlɒŋ wɪð/', 'I get along with my coworkers.', 'Relationships', 'A2', 'phrasal verb', 'To have a friendly relationship with someone.', ARRAY['I get along with my coworkers.', 'She doesn''t get along with her sister.', 'They get along really well.'], NULL, 'neutral', 'Relationships'),
  ('en-vocab-v2-forecast', 'en', 'Forecast', 'Pronóstico', '/ˈfɔːr.kæst/', 'The forecast says it will rain tomorrow.', 'Nature', 'A2', 'noun', 'A prediction of future weather.', ARRAY['The forecast says it will rain tomorrow.', 'Check the forecast before the trip.', 'The weather forecast was wrong again.'], NULL, 'neutral', 'Weather'),
  ('en-vocab-v2-charger', 'en', 'Charger', 'Cargador', '/ˈtʃɑːr.dʒɚ/', 'I forgot my phone charger at home.', 'Technology', 'A2', 'noun', 'A device used to recharge a battery.', ARRAY['I forgot my phone charger at home.', 'Can I borrow your charger?', 'The charger stopped working.'], NULL, 'neutral', 'Technology'),
  ('en-vocab-v2-crowded', 'en', 'Crowded', 'Concurrido/lleno de gente', '/ˈkraʊ.dɪd/', 'The bus was too crowded to move.', 'Daily Life', 'A2', 'adjective', 'Full of people.', ARRAY['The bus was too crowded to move.', 'Downtown gets crowded on weekends.', 'The restaurant was crowded at lunchtime.'], NULL, 'neutral', 'City'),
  ('en-vocab-v2-figure-out', 'en', 'Figure out', 'Descifrar / entender', '/ˈfɪɡ.jɚ aʊt/', 'I finally figured out how the app works.', 'Technology', 'A2', 'phrasal verb', 'To understand or solve something after thinking about it.', ARRAY['I finally figured out how the app works.', 'Can you figure out what''s wrong with the printer?', 'She figured out the answer on her own.'], NULL, 'neutral', 'Common Phrasal Verbs'),
  ('en-vocab-v2-give-up', 'en', 'Give up', 'Rendirse / dejar de hacer algo', '/ɡɪv ʌp/', 'Don''t give up on your goals.', 'Daily Life', 'A2', 'phrasal verb', 'To stop trying to do something.', ARRAY['Don''t give up on your goals.', 'He gave up smoking last year.', 'She almost gave up during the exam.'], NULL, 'neutral', 'Common Phrasal Verbs')
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- B1 — workplace, communication, emotions, environment, idioms, phrasal
-- verbs, collocations. Synonym/antonym nuance sets start here.
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, synonyms, antonyms, collocations, register, topic, common_mistake)
values
  ('en-vocab-v2-deal-with', 'en', 'Deal with', 'Lidiar con / encargarse de', '/diːl wɪð/', 'I have to deal with a difficult client today.', 'Work', 'B1', 'phrasal verb', 'To handle a problem or situation.', ARRAY['I have to deal with a difficult client today.', 'She deals with complaints calmly.', 'We''ll deal with that issue tomorrow.'], ARRAY['handle', 'manage'], NULL, ARRAY['deal with a problem', 'deal with a complaint'], 'neutral', 'Workplace', NULL),
  ('en-vocab-v2-look-into', 'en', 'Look into', 'Investigar / examinar', '/lʊk ˈɪn.tuː/', 'We''ll look into the matter right away.', 'Work', 'B1', 'phrasal verb', 'To investigate or examine something.', ARRAY['We''ll look into the matter right away.', 'Can you look into why the order is late?', 'The manager looked into the complaint personally.'], ARRAY['investigate', 'examine'], NULL, NULL, 'neutral', 'Workplace', NULL),
  ('en-vocab-v2-annoyed', 'en', 'Annoyed', 'Molesto/a', '/əˈnɔɪd/', 'She was annoyed by the constant noise.', 'Emotions', 'B1', 'adjective', 'Slightly angry; mildly irritated.', ARRAY['She was annoyed by the constant noise.', 'He got annoyed when the bus was late again.', 'I''m a little annoyed, but it''s not a big deal.'], ARRAY['irritated'], ARRAY['pleased'], NULL, 'neutral', 'Emotions', 'Weaker than "furious" — don''t use for real anger.'),
  ('en-vocab-v2-frustrated', 'en', 'Frustrated', 'Frustrado/a', '/frʌsˈtreɪ.tɪd/', 'He felt frustrated after the third failed attempt.', 'Emotions', 'B1', 'adjective', 'Upset because you can''t achieve or fix something.', ARRAY['He felt frustrated after the third failed attempt.', 'I get frustrated when the internet is slow.', 'She sounded frustrated on the call.'], ARRAY['exasperated'], ARRAY['satisfied'], NULL, 'neutral', 'Emotions', NULL),
  ('en-vocab-v2-furious', 'en', 'Furious', 'Furioso/a', '/ˈfjʊr.i.əs/', 'The customer was furious about the extra charge.', 'Emotions', 'B1', 'adjective', 'Extremely angry.', ARRAY['The customer was furious about the extra charge.', 'She was furious when she found out.', 'He slammed the door, furious.'], ARRAY['enraged', 'irate'], ARRAY['calm'], NULL, 'neutral', 'Emotions', 'Much stronger than "annoyed" — reserve for real anger.'),
  ('en-vocab-v2-pollution', 'en', 'Pollution', 'Contaminación', '/pəˈluː.ʃən/', 'Air pollution is worse in big cities.', 'Nature', 'B1', 'noun', 'Harmful substances damaging the air, water, or land.', ARRAY['Air pollution is worse in big cities.', 'The factory was fined for pollution.', 'Traffic is a major source of pollution.'], NULL, NULL, ARRAY['reduce pollution', 'cause pollution'], 'neutral', 'Environment', NULL),
  ('en-vocab-v2-recycle', 'en', 'Recycle', 'Reciclar', '/riːˈsaɪ.kəl/', 'We recycle paper and plastic at home.', 'Nature', 'B1', 'verb', 'To process used materials so they can be used again.', ARRAY['We recycle paper and plastic at home.', 'Does your building recycle glass?', 'They recycled the old furniture into something new.'], NULL, NULL, NULL, 'neutral', 'Environment', NULL),
  ('en-vocab-v2-make-a-decision', 'en', 'Make a decision', 'Tomar una decisión', '/meɪk ə dɪˈsɪʒ.ən/', 'We need to make a decision by Friday.', 'Business', 'B1', 'collocation', 'To choose between options.', ARRAY['We need to make a decision by Friday.', 'It''s hard to make a decision under pressure.', 'She made a quick decision.'], NULL, NULL, ARRAY['make a decision', 'make progress', 'make an effort', 'make a mistake'], 'neutral', 'Communication', NULL),
  ('en-vocab-v2-do-research', 'en', 'Do research', 'Investigar', '/duː rɪˈsɝːtʃ/', 'She did research before buying the laptop.', 'Education', 'B1', 'collocation', 'To study a subject carefully to find information.', ARRAY['She did research before buying the laptop.', 'We need to do more research on this topic.', 'They did research for months before launching.'], NULL, NULL, ARRAY['do research', 'do homework', 'do business'], 'neutral', 'Education', 'Use "do", not "make", with research, homework, and business.'),
  ('en-vocab-v2-opinion', 'en', 'Opinion', 'Opinión', '/əˈpɪn.jən/', 'In my opinion, the plan needs more time.', 'Communication', 'B1', 'noun', 'A personal view or judgment.', ARRAY['In my opinion, the plan needs more time.', 'She shared her opinion during the meeting.', 'What''s your opinion on the new policy?'], ARRAY['viewpoint'], NULL, ARRAY['share an opinion', 'change your opinion'], 'neutral', 'Communication', NULL),
  ('en-vocab-v2-break-the-ice', 'en', 'Break the ice', 'Romper el hielo', '/breɪk ði aɪs/', 'He told a joke to break the ice at the meeting.', 'Communication', 'B1', 'idiom', 'To do or say something to make people feel more relaxed.', ARRAY['He told a joke to break the ice at the meeting.', 'A quick game can break the ice with new students.', 'She broke the ice by asking about his weekend.'], NULL, NULL, NULL, 'neutral', 'Common Idioms', NULL),
  ('en-vocab-v2-career', 'en', 'Career', 'Carrera profesional', '/kəˈrɪr/', 'She built a successful career in marketing.', 'Work', 'B1', 'noun', 'A person''s progress through work over time.', ARRAY['She built a successful career in marketing.', 'He''s thinking about a career change.', 'This job could be the start of a great career.'], NULL, NULL, ARRAY['build a career', 'pursue a career'], 'neutral', 'Careers', NULL),
  ('en-vocab-v2-society', 'en', 'Society', 'Sociedad', '/səˈsaɪ.ə.ti/', 'Technology has changed modern society.', 'Society', 'B1', 'noun', 'People living together in an organized community.', ARRAY['Technology has changed modern society.', 'Education benefits society as a whole.', 'Every society has its own customs.'], NULL, NULL, NULL, 'neutral', 'Society', NULL),
  ('en-vocab-v2-solve-a-problem', 'en', 'Solve a problem', 'Resolver un problema', '/sɒlv ə ˈprɒb.ləm/', 'The team worked together to solve the problem.', 'Work', 'B1', 'collocation', 'To find a solution to a difficulty.', ARRAY['The team worked together to solve the problem.', 'It took two days to solve the problem.', 'She solved the problem with a simple fix.'], NULL, NULL, ARRAY['solve a problem', 'face a problem', 'raise a problem'], 'neutral', 'Problem Solving', NULL)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- B2 — professional English, customer service, business, negotiation,
-- leadership, tech, economics, media, psychology, law, finance. Advanced
-- phrasal verbs, collocations, idioms, formal vocabulary, word formation.
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, synonyms, antonyms, collocations, register, topic, related_words, common_mistake)
values
  ('en-vocab-v2-escalate', 'en', 'Escalate', 'Escalar (un problema)', '/ˈes.kə.leɪt/', 'I had to escalate the ticket to a supervisor.', 'Customer Service', 'B2', 'verb', 'To pass a problem to someone with more authority when it can''t be resolved at the current level.', ARRAY['I had to escalate the ticket to a supervisor.', 'Please escalate any billing disputes to Tier 2.', 'The issue was escalated after the second complaint.', 'We escalate calls that go over ten minutes.'], ARRAY['refer up', 'raise'], NULL, ARRAY['escalate an issue', 'escalate a complaint'], 'formal', 'Call Center', ARRAY['en-vocab-v2-escalation'], NULL),
  ('en-vocab-v2-escalation', 'en', 'Escalation', 'Escalamiento', '/ˌes.kəˈleɪ.ʃən/', 'The escalation team handles unresolved cases.', 'Customer Service', 'B2', 'noun', 'The act of passing a problem to a higher authority.', ARRAY['The escalation team handles unresolved cases.', 'We track the average escalation rate weekly.', 'His escalation was resolved within the hour.'], NULL, NULL, NULL, 'formal', 'Call Center', ARRAY['en-vocab-v2-escalate'], NULL),
  ('en-vocab-v2-refund-b2', 'en', 'Refund', 'Reembolso', '/ˈriː.fʌnd/', 'The customer requested a full refund.', 'Customer Service', 'B2', 'noun', 'Money given back after a purchase is returned or cancelled.', ARRAY['The customer requested a full refund.', 'We processed the refund within 48 hours.', 'She asked for a refund instead of a replacement.', 'Refunds are issued to the original payment method.'], NULL, NULL, ARRAY['request a refund', 'process a refund', 'issue a refund'], 'neutral', 'Call Center', NULL, NULL),
  ('en-vocab-v2-troubleshoot', 'en', 'Troubleshoot', 'Solucionar problemas técnicos', '/ˈtrʌb.əl.ʃuːt/', 'Let''s troubleshoot the connection issue together.', 'Technology', 'B2', 'verb', 'To identify and fix the cause of a technical problem.', ARRAY['Let''s troubleshoot the connection issue together.', 'I troubleshot the printer for twenty minutes.', 'Our team troubleshoots most issues remotely.'], NULL, NULL, ARRAY['troubleshoot an issue'], 'neutral', 'Technical Support', NULL, NULL),
  ('en-vocab-v2-retention', 'en', 'Retention', 'Retención (de clientes)', '/rɪˈten.ʃən/', 'The retention team offered her a discount to stay.', 'Business', 'B2', 'noun', 'Keeping existing customers rather than losing them.', ARRAY['The retention team offered her a discount to stay.', 'Customer retention improved after the new plan.', 'Retention is cheaper than acquiring new customers.'], NULL, NULL, ARRAY['customer retention', 'retention rate'], 'formal', 'Customer Service', NULL, NULL),
  ('en-vocab-v2-churn', 'en', 'Churn', 'Tasa de cancelación de clientes', '/tʃɝːn/', 'Churn increased after the price change.', 'Business', 'B2', 'noun', 'The rate at which customers stop using a service.', ARRAY['Churn increased after the price change.', 'We track monthly churn closely.', 'High churn hurts long-term revenue.'], NULL, NULL, ARRAY['reduce churn', 'churn rate'], 'formal', 'Customer Service', NULL, NULL),
  ('en-vocab-v2-negotiate-b2', 'en', 'Negotiate', 'Negociar', '/nɪˈɡoʊ.ʃi.eɪt/', 'They negotiated a better contract with the supplier.', 'Business', 'B2', 'verb', 'To discuss something in order to reach an agreement.', ARRAY['They negotiated a better contract with the supplier.', 'We negotiated the deadline with the client.', 'She''s good at negotiating salaries.'], ARRAY['bargain'], NULL, ARRAY['negotiate a deal', 'negotiate terms'], 'neutral', 'Negotiation', ARRAY['en-vocab-v2-negotiation'], NULL),
  ('en-vocab-v2-negotiation', 'en', 'Negotiation', 'Negociación', '/nɪˌɡoʊ.ʃiˈeɪ.ʃən/', 'The negotiation lasted two hours.', 'Business', 'B2', 'noun', 'The process of discussing something to reach an agreement.', ARRAY['The negotiation lasted two hours.', 'Both sides entered the negotiation prepared.', 'Salary negotiation can feel uncomfortable.'], NULL, NULL, NULL, 'neutral', 'Negotiation', ARRAY['en-vocab-v2-negotiate-b2'], NULL),
  ('en-vocab-v2-take-over', 'en', 'Take over', 'Tomar el control / hacerse cargo', '/teɪk ˈoʊ.vɚ/', 'She took over the project when the manager left.', 'Leadership', 'B2', 'phrasal verb', 'To take control of something.', ARRAY['She took over the project when the manager left.', 'The new CEO took over in March.', 'Can you take over this call for me?'], NULL, NULL, NULL, 'neutral', 'Leadership', NULL, NULL),
  ('en-vocab-v2-turn-down', 'en', 'Turn down', 'Rechazar', '/tɝːn daʊn/', 'He turned down the promotion.', 'Work', 'B2', 'phrasal verb', 'To refuse an offer or request.', ARRAY['He turned down the promotion.', 'They turned down our proposal.', 'She turned the offer down politely.'], ARRAY['reject', 'decline'], ARRAY['accept'], NULL, 'neutral', 'Work', NULL, NULL),
  ('en-vocab-v2-set-up', 'en', 'Set up', 'Configurar / establecer', '/set ʌp/', 'IT will set up your account today.', 'Technology', 'B2', 'phrasal verb', 'To arrange or prepare something so it is ready.', ARRAY['IT will set up your account today.', 'We set up the meeting for 3 PM.', 'She set up her own business last year.'], NULL, NULL, NULL, 'neutral', 'Technology', NULL, NULL),
  ('en-vocab-v2-work-out', 'en', 'Work out', 'Resultar bien / calcular', '/wɝːk aʊt/', 'The new schedule worked out well for everyone.', 'Work', 'B2', 'phrasal verb', 'To develop in a successful way, or to calculate something.', ARRAY['The new schedule worked out well for everyone.', 'Can you work out the total cost?', 'I hope this plan works out.'], NULL, NULL, NULL, 'neutral', 'Work', NULL, NULL),
  ('en-vocab-v2-come-across', 'en', 'Come across', 'Encontrarse con / dar la impresión de', '/kʌm əˈkrɒs/', 'I came across an old email about this.', 'Daily Life', 'B2', 'phrasal verb', 'To find something by chance, or to give a particular impression.', ARRAY['I came across an old email about this.', 'He came across as confident in the interview.', 'We came across a great restaurant downtown.'], NULL, NULL, NULL, 'neutral', 'Communication', NULL, NULL),
  ('en-vocab-v2-carry-out', 'en', 'Carry out', 'Llevar a cabo / realizar', '/ˈkær.i aʊt/', 'The team carried out a full inspection.', 'Work', 'B2', 'phrasal verb', 'To do or perform a task or plan.', ARRAY['The team carried out a full inspection.', 'We carry out surveys every quarter.', 'The instructions were carried out precisely.'], ARRAY['perform', 'conduct'], NULL, NULL, 'formal', 'Workplace', NULL, NULL),
  ('en-vocab-v2-follow-up', 'en', 'Follow up', 'Dar seguimiento', '/ˈfɒl.oʊ ʌp/', 'I''ll follow up with you next week.', 'Work', 'B2', 'phrasal verb', 'To check on the progress of something or contact someone again.', ARRAY['I''ll follow up with you next week.', 'Please follow up on the shipment status.', 'She followed up after the interview.'], NULL, NULL, ARRAY['follow up on', 'follow-up call'], 'neutral', 'Workplace', NULL, NULL),
  ('en-vocab-v2-word-formation-communicate', 'en', 'Communicate', 'Comunicar', '/kəˈmjuː.nə.keɪt/', 'Good teams communicate clearly.', 'Communication', 'B2', 'verb', 'To share information with others.', ARRAY['Good teams communicate clearly.', 'We communicate mostly by email.', 'She communicates well under pressure.'], NULL, NULL, NULL, 'neutral', 'Word Formation', ARRAY['en-vocab-v2-word-formation-communication', 'en-vocab-v2-word-formation-communicative'], NULL),
  ('en-vocab-v2-word-formation-communication', 'en', 'Communication', 'Comunicación', '/kəˌmjuː.nəˈkeɪ.ʃən/', 'Communication broke down during the outage.', 'Communication', 'B2', 'noun', 'The act of sharing or exchanging information.', ARRAY['Communication broke down during the outage.', 'Clear communication prevents most conflicts.', 'The team improved internal communication.'], NULL, NULL, NULL, 'neutral', 'Word Formation', ARRAY['en-vocab-v2-word-formation-communicate', 'en-vocab-v2-word-formation-communicative'], NULL),
  ('en-vocab-v2-word-formation-communicative', 'en', 'Communicative', 'Comunicativo', '/kəˈmjuː.nə.kə.tɪv/', 'She''s naturally communicative with clients.', 'Communication', 'B2', 'adjective', 'Willing and able to share information easily.', ARRAY['She''s naturally communicative with clients.', 'A communicative style helps in customer service.', 'He became more communicative after training.'], NULL, ARRAY['reserved'], NULL, 'neutral', 'Word Formation', ARRAY['en-vocab-v2-word-formation-communicate', 'en-vocab-v2-word-formation-communication'], NULL),
  ('en-vocab-v2-media-b2', 'en', 'Media', 'Medios de comunicación', '/ˈmiː.di.ə/', 'The story spread quickly on social media.', 'Media', 'B2', 'noun', 'The channels used to communicate news and information to the public.', ARRAY['The story spread quickly on social media.', 'Traditional media covered the launch.', 'She works in media relations.'], NULL, NULL, NULL, 'neutral', 'Media', NULL, NULL),
  ('en-vocab-v2-psychology-b2', 'en', 'Mindset', 'Mentalidad', '/ˈmaɪnd.set/', 'A growth mindset helps you learn from mistakes.', 'Education', 'B2', 'noun', 'A person''s usual way of thinking about things.', ARRAY['A growth mindset helps you learn from mistakes.', 'She approaches problems with a positive mindset.', 'Changing your mindset takes practice.'], NULL, NULL, NULL, 'neutral', 'Psychology', NULL, NULL)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- C1 — academic/professional English, business, economics, psychology,
-- technology, ethics, communication, social issues. Collocations, idioms,
-- discourse markers, nuanced synonyms, abstract vocabulary, register.
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, synonyms, antonyms, collocations, register, topic, common_mistake)
values
  ('en-vocab-v2-nevertheless', 'en', 'Nevertheless', 'Sin embargo / no obstante', '/ˌnev.ɚ.ðəˈles/', 'The results were disappointing; nevertheless, we learned a lot.', 'Communication', 'C1', 'discourse marker', 'Used to introduce a statement that contrasts with what came before.', ARRAY['The results were disappointing; nevertheless, we learned a lot.', 'It was raining. Nevertheless, they went for a walk.', 'Nevertheless, the team met the deadline.'], ARRAY['however', 'nonetheless'], NULL, NULL, 'formal', 'Discourse Markers', 'Too formal for casual speech — use "but" or "still" with friends.'),
  ('en-vocab-v2-furthermore', 'en', 'Furthermore', 'Además / asimismo', '/ˈfɝː.ðɚ.mɔːr/', 'The proposal is cost-effective. Furthermore, it improves customer satisfaction.', 'Communication', 'C1', 'discourse marker', 'Used to add a further point, usually in formal writing or speech.', ARRAY['The proposal is cost-effective. Furthermore, it improves customer satisfaction.', 'Furthermore, the data supports our conclusion.', 'The plan saves money; furthermore, it saves time.'], ARRAY['moreover', 'in addition'], NULL, NULL, 'formal', 'Discourse Markers', NULL),
  ('en-vocab-v2-leverage-c1', 'en', 'Leverage', 'Aprovechar / apalancar', '/ˈlev.ɚ.ɪdʒ/', 'We can leverage customer data to personalize service.', 'Business', 'C1', 'verb', 'To use something you already have to gain an advantage.', ARRAY['We can leverage customer data to personalize service.', 'The company leveraged its brand reputation to enter a new market.', 'She leveraged her network to find the job.'], ARRAY['capitalize on', 'utilize'], NULL, ARRAY['leverage resources', 'leverage experience'], 'formal', 'Business', NULL),
  ('en-vocab-v2-mitigate-c1', 'en', 'Mitigate', 'Mitigar', '/ˈmɪt.ə.ɡeɪt/', 'We updated the process to mitigate future errors.', 'Business', 'C1', 'verb', 'To make something less severe or harmful.', ARRAY['We updated the process to mitigate future errors.', 'The new policy mitigates the risk of data loss.', 'Training helps mitigate customer complaints.'], ARRAY['alleviate', 'reduce'], ARRAY['aggravate'], ARRAY['mitigate risk', 'mitigate the impact'], 'formal', 'Business', NULL),
  ('en-vocab-v2-discrepancy-c1', 'en', 'Discrepancy', 'Discrepancia', '/dɪˈskrep.ən.si/', 'There''s a discrepancy between the invoice and the order.', 'Finance', 'C1', 'noun', 'A difference between things that should be the same.', ARRAY['There''s a discrepancy between the invoice and the order.', 'The audit found several discrepancies in the report.', 'We resolved the discrepancy within a day.'], ARRAY['inconsistency'], NULL, NULL, 'formal', 'Finance', NULL),
  ('en-vocab-v2-accountability', 'en', 'Accountability', 'Responsabilidad (rendición de cuentas)', '/əˌkaʊn.təˈbɪl.ə.ti/', 'The new system increases accountability across teams.', 'Leadership', 'C1', 'noun', 'Being responsible for your actions and having to explain them.', ARRAY['The new system increases accountability across teams.', 'Good leaders promote accountability, not blame.', 'There was little accountability for the delay.'], NULL, NULL, ARRAY['personal accountability', 'lack of accountability'], 'formal', 'Leadership', NULL),
  ('en-vocab-v2-ethical', 'en', 'Ethical', 'Ético', '/ˈeθ.ɪ.kəl/', 'The company follows strict ethical guidelines.', 'Society', 'C1', 'adjective', 'Relating to what is morally right and wrong.', ARRAY['The company follows strict ethical guidelines.', 'It raises an ethical question about data privacy.', 'She made the ethical choice despite the cost.'], NULL, ARRAY['unethical'], NULL, 'formal', 'Ethics', NULL),
  ('en-vocab-v2-inequality', 'en', 'Inequality', 'Desigualdad', '/ˌɪn.ɪˈkwɒl.ə.ti/', 'The report highlights growing income inequality.', 'Society', 'C1', 'noun', 'An unfair difference between groups in society.', ARRAY['The report highlights growing income inequality.', 'Education can help reduce inequality.', 'Inequality remains a major social issue.'], NULL, NULL, ARRAY['income inequality', 'social inequality'], 'formal', 'Social Issues', NULL),
  ('en-vocab-v2-algorithm', 'en', 'Algorithm', 'Algoritmo', '/ˈæl.ɡə.rɪ.ðəm/', 'The app uses an algorithm to recommend content.', 'Technology', 'C1', 'noun', 'A set of rules a computer follows to solve a problem or perform a task.', ARRAY['The app uses an algorithm to recommend content.', 'Engineers improved the search algorithm.', 'The algorithm flagged the transaction as suspicious.'], NULL, NULL, NULL, 'formal', 'Technology', NULL),
  ('en-vocab-v2-cognitive-bias', 'en', 'Cognitive bias', 'Sesgo cognitivo', '/ˈkɒɡ.nə.tɪv ˈbaɪ.əs/', 'Confirmation bias is a common cognitive bias.', 'Education', 'C1', 'noun', 'A systematic error in thinking that affects judgment.', ARRAY['Confirmation bias is a common cognitive bias.', 'Understanding cognitive bias improves decision-making.', 'The training covered several cognitive biases.'], NULL, NULL, NULL, 'formal', 'Psychology', NULL),
  ('en-vocab-v2-a-double-edged-sword', 'en', 'A double-edged sword', 'Un arma de doble filo', '/ə ˈdʌb.əl edʒd sɔːrd/', 'Automation is a double-edged sword — efficient but costly to jobs.', 'Society', 'C1', 'idiom', 'Something that has both good and bad effects.', ARRAY['Automation is a double-edged sword — efficient but costly to jobs.', 'Social media is a double-edged sword for small businesses.', 'Fast growth can be a double-edged sword.'], NULL, NULL, NULL, 'neutral', 'Common Idioms', NULL),
  ('en-vocab-v2-get-the-ball-rolling', 'en', 'Get the ball rolling', 'Poner las cosas en marcha', '/ɡet ðə bɔːl ˈroʊ.lɪŋ/', 'Let''s get the ball rolling on the new project.', 'Work', 'C1', 'idiom', 'To start a process or activity.', ARRAY['Let''s get the ball rolling on the new project.', 'She got the ball rolling with a short introduction.', 'We need someone to get the ball rolling on this.'], NULL, NULL, NULL, 'neutral', 'Common Idioms', NULL),
  ('en-vocab-v2-articulate', 'en', 'Articulate', 'Expresar con claridad', '/ɑːrˈtɪk.jə.leɪt/', 'She articulated her concerns clearly during the review.', 'Communication', 'C1', 'verb', 'To express an idea or feeling clearly in words.', ARRAY['She articulated her concerns clearly during the review.', 'He struggled to articulate what went wrong.', 'The report articulates a clear strategy.'], ARRAY['express', 'convey'], NULL, NULL, 'formal', 'Communication', NULL),
  ('en-vocab-v2-comprehensive', 'en', 'Comprehensive', 'Integral / exhaustivo', '/ˌkɒm.prɪˈhen.sɪv/', 'We conducted a comprehensive review of the policy.', 'Business', 'C1', 'adjective', 'Complete and including everything necessary.', ARRAY['We conducted a comprehensive review of the policy.', 'The training offers comprehensive coverage of the software.', 'Her report was thorough and comprehensive.'], ARRAY['thorough', 'exhaustive'], ARRAY['partial'], NULL, 'formal', 'Business', NULL)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- C2 — nuance, register, precision, sophisticated connectors, rhetorical
-- and academic vocabulary. Includes the "big" intensity ladder from the
-- spec brief (big/large/substantial/considerable/enormous/massive/
-- significant) so Register/Nuance Challenge has a real set to test.
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, synonyms, register, topic, common_mistake)
values
  ('en-vocab-v2-big', 'en', 'Big', 'Grande', '/bɪɡ/', 'That''s a big change for the team.', 'Daily Life', 'A2', 'adjective', 'Large in size, amount, or degree.', ARRAY['That''s a big change for the team.', 'We have a big meeting today.', 'It was a big decision to make.'], ARRAY['large'], 'casual', 'Nuance: Size & Scale', NULL),
  ('en-vocab-v2-substantial', 'en', 'Substantial', 'Sustancial / considerable', '/səbˈstæn.ʃəl/', 'The company reported a substantial increase in revenue.', 'Business', 'C1', 'adjective', 'Large in amount or degree, often used for measurable things like money or data.', ARRAY['The company reported a substantial increase in revenue.', 'There was a substantial improvement in response times.', 'They made a substantial investment in training.'], ARRAY['considerable'], 'formal', 'Nuance: Size & Scale', 'Sounds odd for physical size ("a substantial dog") — use it for amounts, changes, and evidence.'),
  ('en-vocab-v2-considerable', 'en', 'Considerable', 'Considerable', '/kənˈsɪd.ɚ.ə.bəl/', 'It will take a considerable amount of time.', 'Business', 'C1', 'adjective', 'Large enough to be important or have an effect.', ARRAY['It will take a considerable amount of time.', 'The project required considerable effort.', 'There was considerable interest in the announcement.'], ARRAY['substantial', 'significant'], 'formal', 'Nuance: Size & Scale', NULL),
  ('en-vocab-v2-enormous', 'en', 'Enormous', 'Enorme', '/ɪˈnɔːr.məs/', 'The warehouse is enormous.', 'Daily Life', 'B2', 'adjective', 'Extremely large in physical size.', ARRAY['The warehouse is enormous.', 'She felt an enormous sense of relief.', 'They live in an enormous house.'], ARRAY['massive', 'huge'], 'neutral', 'Nuance: Size & Scale', NULL),
  ('en-vocab-v2-massive', 'en', 'Massive', 'Masivo / enorme', '/ˈmæs.ɪv/', 'The update caused a massive drop in errors.', 'Technology', 'B2', 'adjective', 'Very large, often used informally for emphasis.', ARRAY['The update caused a massive drop in errors.', 'That''s a massive improvement.', 'We had a massive turnout at the event.'], ARRAY['enormous', 'huge'], 'casual', 'Nuance: Size & Scale', 'More casual than "substantial" — avoid in very formal reports.'),
  ('en-vocab-v2-significant', 'en', 'Significant', 'Significativo', '/sɪɡˈnɪf.ə.kənt/', 'There was a significant improvement in customer satisfaction.', 'Business', 'C1', 'adjective', 'Large or important enough to be noticed or to matter.', ARRAY['There was a significant improvement in customer satisfaction.', 'The findings are statistically significant.', 'This represents a significant change in policy.'], ARRAY['considerable', 'substantial'], 'formal', 'Nuance: Size & Scale', 'Means "important", not just "big" — a small but meaningful change can still be "significant".'),
  ('en-vocab-v2-ubiquitous-c2', 'en', 'Ubiquitous', 'Omnipresente', '/juːˈbɪk.wə.təs/', 'Chatbots have become ubiquitous in customer service.', 'Technology', 'C2', 'adjective', 'Present or seen everywhere.', ARRAY['Chatbots have become ubiquitous in customer service.', 'Smartphones are now ubiquitous.', 'The brand''s logo is ubiquitous in the city.'], NULL, 'formal', 'Precision Vocabulary', NULL),
  ('en-vocab-v2-nuanced-c2', 'en', 'Nuanced', 'Matizado', '/ˈnuː.ɑːnst/', 'Her answer was more nuanced than a simple yes or no.', 'Education', 'C2', 'adjective', 'Showing subtle differences or shades of meaning.', ARRAY['Her answer was more nuanced than a simple yes or no.', 'The policy requires a nuanced approach.', 'His feedback was nuanced and specific.'], NULL, 'formal', 'Precision Vocabulary', NULL),
  ('en-vocab-v2-tacit-c2', 'en', 'Tacit', 'Tácito / implícito', '/ˈtæs.ɪt/', 'There was a tacit agreement not to discuss it further.', 'Business', 'C2', 'adjective', 'Understood or implied without being directly stated.', ARRAY['There was a tacit agreement not to discuss it further.', 'His silence was taken as tacit approval.', 'They reached a tacit understanding.'], ARRAY['implicit', 'unspoken'], 'formal', 'Precision Vocabulary', NULL),
  ('en-vocab-v2-pragmatic-c2', 'en', 'Pragmatic', 'Pragmático', '/præɡˈmæt.ɪk/', 'We took a pragmatic approach rather than an ideal one.', 'Work', 'C2', 'adjective', 'Dealing with problems in a practical, realistic way.', ARRAY['We took a pragmatic approach rather than an ideal one.', 'She''s pragmatic about what the budget allows.', 'A pragmatic solution beats a perfect one that never ships.'], NULL, 'formal', 'Precision Vocabulary', NULL),
  ('en-vocab-v2-in-light-of', 'en', 'In light of', 'A la luz de / dado que', '/ɪn laɪt ʌv/', 'In light of recent events, we''ve updated the policy.', 'Communication', 'C2', 'discourse marker', 'Considering or because of a particular fact.', ARRAY['In light of recent events, we''ve updated the policy.', 'In light of the feedback, we revised the proposal.', 'In light of the delay, the deadline was extended.'], NULL, 'formal', 'Discourse Markers', NULL),
  ('en-vocab-v2-that-said', 'en', 'That said', 'Dicho esto / aun así', '/ðæt sed/', 'The results were mixed. That said, we''re optimistic.', 'Communication', 'C2', 'discourse marker', 'Used to introduce a contrasting point after acknowledging something.', ARRAY['The results were mixed. That said, we''re optimistic.', 'It''s expensive. That said, it''s worth it.', 'That said, there''s still room for improvement.'], ARRAY['nevertheless'], 'neutral', 'Discourse Markers', NULL)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- Polysemy set (§16) — the same headword taught across its distinct senses,
-- each a separate row (own id, definition, example, translation) so the
-- engine can present them as different "cards" and Nuance Challenge can
-- contrast them. B2/C1, per the spec's emphasis for these levels.
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, register, topic, sense)
values
  ('en-vocab-v2-charge-bill', 'en', 'Charge', 'Cobrar', '/tʃɑːrdʒ/', 'We charge a small fee for late returns.', 'Finance', 'B2', 'verb', 'To ask someone to pay an amount of money.', ARRAY['We charge a small fee for late returns.', 'They charged me twice for the same order.', 'How much do you charge for delivery?'], 'neutral', 'Polysemy: charge', 'to bill / ask payment'),
  ('en-vocab-v2-charge-accuse', 'en', 'Charge', 'Acusar', '/tʃɑːrdʒ/', 'He was charged with fraud.', 'Society', 'C1', 'verb', 'To formally accuse someone of a crime.', ARRAY['He was charged with fraud.', 'Police charged the driver with speeding.', 'She was never officially charged.'], 'formal', 'Polysemy: charge', 'to accuse (legal)'),
  ('en-vocab-v2-charge-noun', 'en', 'Charge', 'Cargo (a cuenta)', '/tʃɑːrdʒ/', 'There''s an extra charge for baggage.', 'Finance', 'B2', 'noun', 'An amount of money you have to pay for something.', ARRAY['There''s an extra charge for baggage.', 'The service charge is included.', 'We disputed the charge on our statement.'], 'neutral', 'Polysemy: charge', 'a fee (noun)'),
  ('en-vocab-v2-charge-battery', 'en', 'Charge', 'Cargar (batería)', '/tʃɑːrdʒ/', 'Please charge your headset before the shift.', 'Technology', 'A2', 'verb', 'To fill a device with electrical power.', ARRAY['Please charge your headset before the shift.', 'My phone is fully charged.', 'I forgot to charge my laptop overnight.'], 'neutral', 'Polysemy: charge', 'to power up a device'),
  ('en-vocab-v2-issue-problem', 'en', 'Issue', 'Problema', '/ˈɪʃ.uː/', 'I''ll look into the issue right away.', 'Customer Service', 'B1', 'noun', 'A problem or difficulty.', ARRAY['I''ll look into the issue right away.', 'We''re experiencing a technical issue.', 'The delivery issue was resolved.'], 'neutral', 'Polysemy: issue', 'a problem'),
  ('en-vocab-v2-issue-security', 'en', 'Issue', 'Fallo (de seguridad)', '/ˈɪʃ.uː/', 'We identified a security issue in the update.', 'Technology', 'B2', 'noun', 'A weakness or bug, especially in software or security.', ARRAY['We identified a security issue in the update.', 'The patch fixes a critical issue.', 'Engineers are reviewing the issue now.'], 'formal', 'Polysemy: issue', 'a bug or vulnerability'),
  ('en-vocab-v2-issue-topic', 'en', 'Issue', 'Tema / asunto', '/ˈɪʃ.uː/', 'We need to discuss this issue at the meeting.', 'Work', 'B1', 'noun', 'A subject or topic that people discuss or disagree about.', ARRAY['We need to discuss this issue at the meeting.', 'Climate change is a global issue.', 'It''s a sensitive issue for the team.'], 'neutral', 'Polysemy: issue', 'a topic under discussion'),
  ('en-vocab-v2-run-manage', 'en', 'Run', 'Dirigir / administrar', '/rʌn/', 'She runs a small business downtown.', 'Business', 'B1', 'verb', 'To manage or be in charge of something.', ARRAY['She runs a small business downtown.', 'He ran the department for ten years.', 'They run the call center on two shifts.'], 'neutral', 'Polysemy: run', 'to manage'),
  ('en-vocab-v2-run-operate', 'en', 'Run', 'Funcionar / ejecutar', '/rʌn/', 'The software runs on any device.', 'Technology', 'B1', 'verb', 'To operate or function, especially for machines or programs.', ARRAY['The software runs on any device.', 'The engine runs smoothly now.', 'We ran the report overnight.'], 'neutral', 'Polysemy: run', 'to operate/execute'),
  ('en-vocab-v2-run-move', 'en', 'Run', 'Correr', '/rʌn/', 'He runs five kilometers every morning.', 'Health', 'A2', 'verb', 'To move quickly on foot.', ARRAY['He runs five kilometers every morning.', 'She ran to catch the bus.', 'They run together on weekends.'], 'neutral', 'Polysemy: run', 'to move on foot'),
  ('en-vocab-v2-hold-grip', 'en', 'Hold', 'Sostener / agarrar', '/hoʊld/', 'She held the phone close to hear better.', 'Daily Life', 'A2', 'verb', 'To carry or have something in your hands.', ARRAY['She held the phone close to hear better.', 'Can you hold this for a second?', 'He held the door open.'], 'neutral', 'Polysemy: hold', 'to grip physically'),
  ('en-vocab-v2-hold-wait', 'en', 'Hold', 'Esperar (en línea)', '/hoʊld/', 'Please hold while I transfer your call.', 'Call Center', 'B1', 'verb', 'To wait, especially on the phone.', ARRAY['Please hold while I transfer your call.', 'She was on hold for ten minutes.', 'Can you hold for a moment?'], 'formal', 'Polysemy: hold', 'to wait on a call'),
  ('en-vocab-v2-point-idea', 'en', 'Point', 'Punto / idea principal', '/pɔɪnt/', 'That''s a good point — let''s consider it.', 'Communication', 'B1', 'noun', 'An idea or opinion expressed.', ARRAY['That''s a good point — let''s consider it.', 'The main point of the email was unclear.', 'She made an interesting point.'], 'neutral', 'Polysemy: point', 'an idea or argument'),
  ('en-vocab-v2-point-purpose', 'en', 'Point', 'Sentido / propósito', '/pɔɪnt/', 'What''s the point of complaining if nothing changes?', 'Communication', 'B2', 'noun', 'The purpose or reason for something.', ARRAY['What''s the point of complaining if nothing changes?', 'There''s no point rushing if the data is wrong.', 'I see the point of the new policy now.'], 'neutral', 'Polysemy: point', 'purpose/reason')
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- Call center / customer service career-prep vocabulary (§34) — feeds
-- Vocabulary, and is reused by Interview Prep / Roleplay via shared terms.
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, collocations, register, topic)
values
  ('en-vocab-v2-first-call-resolution', 'en', 'First-call resolution', 'Resolución en la primera llamada', '/fɝːst kɔːl ˌrez.əˈluː.ʃən/', 'Our first-call resolution rate improved this quarter.', 'Call Center', 'B2', 'noun', 'Solving a customer''s issue during their first contact, without a follow-up.', ARRAY['Our first-call resolution rate improved this quarter.', 'Agents are trained to aim for first-call resolution.', 'Low first-call resolution increases customer frustration.'], NULL, 'formal', 'Call Center'),
  ('en-vocab-v2-average-handle-time', 'en', 'Average handle time', 'Tiempo promedio de atención', '/ˈæv.ər.ɪdʒ ˈhæn.dəl taɪm/', 'Average handle time dropped after the new script.', 'Call Center', 'B2', 'noun', 'The average duration of a customer interaction, including hold and after-call work.', ARRAY['Average handle time dropped after the new script.', 'We monitor average handle time daily.', 'High average handle time can hurt other metrics.'], NULL, 'formal', 'Call Center'),
  ('en-vocab-v2-quality-assurance', 'en', 'Quality assurance', 'Aseguramiento de calidad', '/ˈkwɒl.ə.ti əˈʃʊr.əns/', 'Quality assurance reviews five calls per agent monthly.', 'Call Center', 'B2', 'noun', 'The process of checking that work meets a required standard.', ARRAY['Quality assurance reviews five calls per agent monthly.', 'She moved from agent to quality assurance.', 'Quality assurance flagged the call for coaching.'], NULL, 'formal', 'Call Center'),
  ('en-vocab-v2-csat', 'en', 'CSAT', 'Satisfacción del cliente', '/ˌsiː.esˈeɪ.tiː/', 'Our CSAT score rose to 92% this month.', 'Call Center', 'C1', 'noun', 'Customer satisfaction score, usually from a post-call survey.', ARRAY['Our CSAT score rose to 92% this month.', 'Low CSAT triggers a follow-up review.', 'We track CSAT alongside first-call resolution.'], NULL, 'formal', 'Call Center'),
  ('en-vocab-v2-upsell', 'en', 'Upsell', 'Venta adicional', '/ˈʌp.sel/', 'He upsold the customer to the premium plan.', 'Sales', 'B2', 'verb', 'To persuade a customer to buy a more expensive product or add-on.', ARRAY['He upsold the customer to the premium plan.', 'Agents are encouraged to upsell when relevant.', 'She upsold three customers this week.'], ARRAY['upsell a customer', 'upsell an add-on'], 'neutral', 'Sales'),
  ('en-vocab-v2-chargeback', 'en', 'Chargeback', 'Contracargo', '/ˈtʃɑːrdʒ.bæk/', 'The bank issued a chargeback after the dispute.', 'Finance', 'C1', 'noun', 'A forced refund initiated by a customer''s bank after a disputed charge.', ARRAY['The bank issued a chargeback after the dispute.', 'Chargebacks cost the company more than refunds.', 'We investigate every chargeback claim.'], NULL, 'formal', 'Billing'),
  ('en-vocab-v2-account-verification', 'en', 'Account verification', 'Verificación de cuenta', '/əˈkaʊnt ˌver.ə.fɪˈkeɪ.ʃən/', 'We need account verification before making changes.', 'Call Center', 'B1', 'noun', 'Confirming a customer''s identity before granting access or making changes.', ARRAY['We need account verification before making changes.', 'Account verification takes about a minute.', 'She completed account verification over the phone.'], NULL, 'formal', 'Call Center'),
  ('en-vocab-v2-empathize', 'en', 'Empathize', 'Mostrar empatía', '/ˈem.pə.θaɪz/', 'Always empathize before offering a solution.', 'Call Center', 'B2', 'verb', 'To understand and share the feelings of another person.', ARRAY['Always empathize before offering a solution.', 'She empathized with the frustrated customer.', 'Empathizing builds trust quickly.'], NULL, 'neutral', 'Call Center'),
  ('en-vocab-v2-de-escalate', 'en', 'De-escalate', 'Calmar / bajar la tensión', '/diː ˈes.kə.leɪt/', 'He de-escalated the situation with a calm tone.', 'Call Center', 'C1', 'verb', 'To reduce the intensity or tension of a conflict.', ARRAY['He de-escalated the situation with a calm tone.', 'Training focuses on how to de-escalate angry callers.', 'She de-escalated the argument before it got worse.'], NULL, 'formal', 'Call Center')
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- Phrasal verb library (§18) — remaining common set not already covered
-- above (find out, bring up, come across as already exist; this adds the
-- rest with meaning + context + activity-ready definition).
-- -----------------------------------------------------------------------------
insert into public.vocabulary_words
  (id, language, term, translation, pronunciation, example, category, level, part_of_speech, definition, examples, register, topic)
values
  ('en-vocab-v2-find-out', 'en', 'Find out', 'Descubrir / averiguar', '/faɪnd aʊt/', 'I need to find out why the order was cancelled.', 'Work', 'B1', 'phrasal verb', 'To discover a piece of information.', ARRAY['I need to find out why the order was cancelled.', 'We found out about the delay too late.', 'Can you find out if the item is in stock?'], 'neutral', 'Phrasal Verbs'),
  ('en-vocab-v2-bring-up-v2', 'en', 'Bring up', 'Sacar un tema / mencionar', '/brɪŋ ʌp/', 'She brought up the delivery issue during the call.', 'Communication', 'B2', 'phrasal verb', 'To introduce a topic in a conversation.', ARRAY['She brought up the delivery issue during the call.', 'He didn''t want to bring up the mistake again.', 'I''ll bring it up at the next meeting.'], 'neutral', 'Phrasal Verbs'),
  ('en-vocab-v2-put-off', 'en', 'Put off', 'Posponer', '/pʊt ɒf/', 'We had to put off the launch by a week.', 'Work', 'B1', 'phrasal verb', 'To delay or postpone something.', ARRAY['We had to put off the launch by a week.', 'Don''t put off the appointment again.', 'She put off replying until Monday.'], 'neutral', 'Phrasal Verbs'),
  ('en-vocab-v2-check-in', 'en', 'Check in', 'Registrarse / hacer check-in', '/tʃek ɪn/', 'Please check in at the front desk.', 'Travel', 'A2', 'phrasal verb', 'To register your arrival at a hotel, airport, or event.', ARRAY['Please check in at the front desk.', 'We checked in two hours before the flight.', 'Guests can check in online now.'], 'neutral', 'Phrasal Verbs'),
  ('en-vocab-v2-catch-up', 'en', 'Catch up', 'Ponerse al día', '/kætʃ ʌp/', 'I need to catch up on my emails.', 'Work', 'B1', 'phrasal verb', 'To reach the same level as others by doing extra work, often after falling behind.', ARRAY['I need to catch up on my emails.', 'Let''s catch up over coffee sometime.', 'She caught up on the training she missed.'], 'neutral', 'Phrasal Verbs')
on conflict (id) do nothing;
