import { CefrLevel, ExerciseType, GrammarTopic } from '../../models';

export const MOCK_GRAMMAR_TOPICS: GrammarTopic[] = [
  // ---------------------------------------------------------------- A1 ----
  {
    id: 'gr-a1-verb-to-be',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Verb "to be"',
    summary: 'Say who you are, how you feel, and where you are.',
    explanation:
      'The verb "to be" changes depending on who you\'re talking about: I am, you are, he/she/it is, we are, they are. Use it for identity ("I am a teacher"), feelings ("She is happy") and location ("We are at home").',
    examples: ['I am from Mexico.', 'You are my friend.', 'It is cold today.'],
    commonMistakes: ['Saying "I is" instead of "I am".', 'Forgetting "to be" in short sentences: "She happy" instead of "She is happy".'],
    order: 1,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct form: "We ___ students."',
        options: ['am', 'is', 'are', 'be'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"He am tired" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a1-pronouns',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Pronouns',
    summary: 'Replace names with I, you, he, she, it, we, they.',
    explanation:
      'Pronouns avoid repeating names. "Maria is a doctor. She works hard" — "she" replaces "Maria". Subject pronouns (I, you, he, she, it, we, they) go before the verb.',
    examples: ['He is my brother.', 'They live in Spain.', 'It is a nice day.'],
    commonMistakes: ['Using "her" instead of "she" as the subject: "Her is nice" is wrong.'],
    order: 2,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: '___ is my sister. She is a nurse.',
        options: ['He', 'She', 'They', 'It'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.MultipleChoice,
        prompt: 'Which pronoun replaces "Tom and Ana"?',
        options: ['He', 'She', 'They', 'We'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a1-present-simple',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Present Simple',
    summary: 'Talk about habits, routines and facts.',
    explanation:
      'Use the Present Simple for things that happen regularly or are generally true. Add "-s" for he/she/it: "I work" but "She works". Use "do/does" for questions and negatives.',
    examples: ['I work every day.', 'She likes coffee.', 'Do you speak English?'],
    commonMistakes: ['Forgetting the "-s": "She work" instead of "She works".'],
    order: 3,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'He ___ to work by bus.',
        options: ['go', 'goes', 'going', 'gone'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"She like pizza" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a1-articles',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Articles',
    summary: '"A", "an" and "the" — when to use each one.',
    explanation:
      'Use "a" before consonant sounds ("a dog") and "an" before vowel sounds ("an apple"). Use "the" when both speakers know which specific thing you mean.',
    examples: ['I have a cat.', 'She ate an orange.', 'The sun is bright today.'],
    commonMistakes: ['Using "a" before a vowel sound: "a apple" instead of "an apple".'],
    order: 4,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct article: "I saw ___ elephant."',
        options: ['a', 'an', 'the', '—'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct article: "Can you close ___ door?" (a specific door)',
        options: ['a', 'an', 'the', '—'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a1-plural-nouns',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Plural nouns',
    summary: 'Talk about more than one thing.',
    explanation:
      'Most nouns add "-s" for plural: "book" → "books". Nouns ending in -s, -x, -ch, -sh add "-es": "box" → "boxes". Some are irregular: "child" → "children".',
    examples: ['I have two cats.', 'She bought three boxes.', 'The children are playing.'],
    commonMistakes: ['Adding "-s" to irregular plurals: "childs" instead of "children".'],
    order: 5,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'What is the plural of "box"?',
        options: ['boxs', 'boxes', 'boxies', 'box'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.MultipleChoice,
        prompt: 'What is the plural of "child"?',
        options: ['childs', 'childes', 'children', 'child'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a1-possessives',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Possessives',
    summary: "Show that something belongs to someone: my, your, Anna's.",
    explanation:
      'Possessive adjectives (my, your, his, her, its, our, their) go before a noun. For names, add \'s: "Anna\'s book". For plural nouns already ending in -s, just add an apostrophe: "the students\' books".',
    examples: ['This is my phone.', "That's Anna's car.", "The dogs' toys are here."],
    commonMistakes: ["Forgetting the apostrophe: \"Anas book\" instead of \"Ana's book\"."],
    order: 6,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'Is this ___ bag? (belonging to you)',
        options: ['you', 'your', "you's", 'yours car'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.MultipleChoice,
        prompt: "Choose the correct possessive form for \"the book of Tom\":",
        options: ["Toms book", "Tom's book", "Toms's book", "Tom books"],
        correctOptionIndex: 1,
        xpReward: 10,
      },
    ],
  },

  // ---------------------------------------------------------------- A2 ----
  {
    id: 'gr-a2-past-simple',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Past Simple',
    summary: 'Talk about finished actions in the past.',
    explanation:
      'Regular verbs add "-ed": "work" → "worked". Irregular verbs change form: "go" → "went", "eat" → "ate". Use "did" for questions and negatives: "Did you go?", "I didn\'t go".',
    examples: ['I worked yesterday.', 'She went to the park.', "They didn't call me."],
    commonMistakes: ['Using "did" and the past form together: "I did went" instead of "I went".'],
    order: 7,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'I ___ to the supermarket yesterday.',
        options: ['go', 'goes', 'went', 'going'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"She didn\'t went home" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a2-future',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Future ("will" / "going to")',
    summary: 'Talk about plans and predictions.',
    explanation:
      'Use "going to" for plans you\'ve already decided: "I\'m going to study tonight". Use "will" for quick decisions or predictions: "I think it will rain".',
    examples: ["I'm going to visit my parents.", 'It will be sunny tomorrow.', "I'll help you."],
    commonMistakes: ['Using "will" for a plan already decided when "going to" fits better (not a hard error, but less natural).'],
    order: 8,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence for a decided plan: "I ___ visit my grandma this weekend."',
        options: ['will', 'am going to', 'go to', 'went to'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"I will going to the party" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a2-comparatives',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Comparatives',
    summary: 'Compare two things: bigger, more expensive, better.',
    explanation:
      'Short adjectives add "-er": "big" → "bigger". Long adjectives use "more": "expensive" → "more expensive". Some are irregular: "good" → "better", "bad" → "worse".',
    examples: ['This car is faster than mine.', 'That book is more interesting.', 'Today is better than yesterday.'],
    commonMistakes: ['Using both forms together: "more bigger" instead of "bigger".'],
    order: 9,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct comparative: "This phone is ___ than that one."',
        options: ['expensive', 'more expensive', 'expensiver', 'most expensive'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.MultipleChoice,
        prompt: 'What is the comparative of "good"?',
        options: ['gooder', 'more good', 'better', 'best'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a2-present-continuous',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Present Continuous',
    summary: 'Talk about things happening right now.',
    explanation:
      'Use "am/is/are + verb-ing" for actions happening at this moment: "I am writing an email right now". Not for habits — that\'s Present Simple.',
    examples: ['She is reading a book.', "They're playing football.", 'I am learning English.'],
    commonMistakes: ['Using it for habits: "I am working every day" instead of "I work every day".'],
    order: 10,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'Look! It ___ outside.',
        options: ['rain', 'rains', 'is raining', 'rained'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"She is work now" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-a2-modal-verbs',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Modal verbs',
    summary: 'Can, must, should — ability, obligation and advice.',
    explanation:
      '"Can" = ability/permission ("I can swim"). "Must" = strong obligation ("You must wear a seatbelt"). "Should" = advice ("You should rest"). Modal verbs never add "-s" and are followed by the base verb.',
    examples: ['She can speak French.', 'You must stop at a red light.', 'You should see a doctor.'],
    commonMistakes: ['Adding "-s": "She cans swim" instead of "She can swim".'],
    order: 11,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence for giving advice:',
        options: ['You should to rest.', 'You should rest.', 'You shoulds rest.', 'You should resting.'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"He can swims very well" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },

  // ---------------------------------------------------------------- B1 ----
  {
    id: 'gr-b1-present-perfect',
    language: 'en',
    level: CefrLevel.B1,
    title: 'Present Perfect',
    summary: 'Connect the past with the present.',
    explanation:
      'Use "have/has + past participle" for experiences ("I have visited Paris") or actions with a present result ("She has just arrived"). Don\'t use it with a specific past time like "yesterday" — use Past Simple for that instead.',
    examples: ['I have seen that movie.', 'He has finished his homework.', "We haven't eaten yet."],
    commonMistakes: ['Mixing it with specific past times: "I have seen it yesterday" instead of "I saw it yesterday".'],
    order: 12,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence.',
        options: [
          'I have seen that movie.',
          'I have saw that movie.',
          'I has seen that movie.',
          'I having seen that movie.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"I have visited Paris last year" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-b1-conditionals',
    language: 'en',
    level: CefrLevel.B1,
    title: 'Conditionals (First & Second)',
    summary: 'Talk about real and imaginary situations.',
    explanation:
      'First conditional = real future possibility: "If it rains, I will stay home". Second conditional = imaginary/unlikely: "If I won the lottery, I would travel the world".',
    examples: ['If I have time, I will call you.', 'If I were you, I would apologize.', "If it rains, we won't go."],
    commonMistakes: ['Using "will" in the "if" clause: "If it will rain" instead of "If it rains".'],
    order: 13,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence:',
        options: [
          'If it rains, I will stay home.',
          'If it will rain, I stay home.',
          'If it rain, I will stay home.',
          'If it rains, I stay home will.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'If I ___ you, I would apologize.',
        options: ['am', 'was', 'were', 'be'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-b1-passive-voice',
    language: 'en',
    level: CefrLevel.B1,
    title: 'Passive voice',
    summary: 'Focus on the action, not who did it.',
    explanation:
      'Use "be + past participle" when the action matters more than who did it: "The window was broken" (we don\'t know or care who broke it). Compare: "Someone broke the window" (active) vs "The window was broken" (passive).',
    examples: ['The email was sent yesterday.', 'This song was written by a famous artist.', 'The bridge is being built.'],
    commonMistakes: ['Forgetting the past participle: "The window was break" instead of "was broken".'],
    order: 14,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct passive sentence:',
        options: [
          'The cake was baked by my mom.',
          'The cake was bake by my mom.',
          'The cake baked was by my mom.',
          'The cake is baked was my mom.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"The letter was wrote by John" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'gr-b1-reported-speech',
    language: 'en',
    level: CefrLevel.B1,
    title: 'Reported speech',
    summary: 'Report what someone else said.',
    explanation:
      'When reporting speech, the verb tense usually moves one step into the past: "I am tired" becomes "She said she was tired". Pronouns and time words often change too: "today" → "that day".',
    examples: [
      '"I am tired" → She said she was tired.',
      '"I will call you" → He said he would call me.',
      '"I have finished" → She said she had finished.',
    ],
    commonMistakes: ['Keeping the original tense: "She said she is tired" instead of "She said she was tired".'],
    order: 15,
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Tom said: "I am busy." How do you report this?',
        options: [
          'Tom said he is busy.',
          'Tom said he was busy.',
          'Tom said he busy.',
          'Tom said I am busy.',
        ],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"I will help you" reported becomes "She said she would help me."',
        correctAnswer: true,
        xpReward: 10,
      },
    ],
  },
];
