import { RoleplayScenario } from '../../models';

export const MOCK_ROLEPLAY_SCENARIOS: RoleplayScenario[] = [
  // ------------------------------------------------------------- Beginner ---
  {
    id: 'rp-1',
    difficulty: 'Beginner',
    category: 'Delivery',
    title: 'Checking an order status',
    context: 'A calm customer wants to know when their package will arrive.',
    objective: 'Verify the order and give a clear status update.',
    customerPersona: 'Calm, polite, just curious.',
    problem: 'Their order has not arrived yet.',
    availableInfo: ['Order was shipped 2 days ago', 'Estimated delivery is tomorrow'],
    expectedResolution: 'Confirm the order and give the estimated delivery date.',
    openingLine: "Hi, I'm just checking — do you know when my order will arrive? It's been a few days.",
  },
  {
    id: 'rp-2',
    difficulty: 'Beginner',
    category: 'Account',
    title: 'Simple password reset',
    context: 'A customer can\'t log into their account.',
    objective: 'Guide them through resetting their password.',
    customerPersona: 'Friendly, a little confused with technology.',
    problem: 'Forgot their password.',
    availableInfo: ['Password reset link is sent by email', 'Link expires in 24 hours'],
    expectedResolution: 'Explain how to reset the password step by step.',
    openingLine: "Hello! I can't log into my account, I think I forgot my password.",
  },
  {
    id: 'rp-3',
    difficulty: 'Beginner',
    category: 'Account',
    title: 'Asking about business hours',
    context: 'A customer wants to know when the store is open.',
    objective: 'Answer clearly and offer further help.',
    customerPersona: 'Polite and brief.',
    problem: 'Wants to know operating hours before visiting.',
    availableInfo: ['Open Monday to Saturday, 9 AM to 7 PM', 'Closed on Sundays'],
    expectedResolution: 'Give the hours clearly and ask if they need anything else.',
    openingLine: 'Hi there, what time does the store close today?',
  },

  // -------------------------------------------------------- Intermediate ---
  {
    id: 'rp-4',
    difficulty: 'Intermediate',
    category: 'Billing',
    title: 'Confused about a bill',
    context: 'A customer doesn\'t understand a charge on their invoice.',
    objective: 'Explain the charge clearly and patiently.',
    customerPersona: 'A bit frustrated, but willing to listen.',
    problem: 'Sees an unfamiliar charge and thinks it\'s a mistake.',
    availableInfo: ['The charge is a one-time setup fee', 'It was mentioned in the original contract'],
    expectedResolution: 'Explain the fee clearly, referencing the contract, and offer to send documentation.',
    openingLine: "I'm looking at my bill and there's a charge I don't recognize. Can you explain this?",
  },
  {
    id: 'rp-5',
    difficulty: 'Intermediate',
    category: 'Delivery',
    title: 'Delayed shipment',
    context: 'A customer\'s order is late and they\'re getting impatient.',
    objective: 'Apologize, explain, and offer a solution.',
    customerPersona: 'Mildly annoyed, expects an explanation.',
    problem: 'Order is 5 days late with no updates.',
    availableInfo: ['Delay caused by a warehouse issue', 'New estimated delivery: 2 more days', 'Can offer a small discount on next order'],
    expectedResolution: 'Apologize, explain the delay honestly, give a new estimate, and offer compensation.',
    openingLine: "This is the third time I'm calling about my order! Where is it?",
  },
  {
    id: 'rp-6',
    difficulty: 'Intermediate',
    category: 'Refund',
    title: 'Wrong item received',
    context: 'A customer got the wrong product in their delivery.',
    objective: 'Apologize and arrange a correction quickly.',
    customerPersona: 'Disappointed but reasonable.',
    problem: 'Ordered a blue jacket, received a red one.',
    availableInfo: ['Free return shipping available', 'Correct item can be sent same day'],
    expectedResolution: 'Apologize, arrange a free return, and send the correct item quickly.',
    openingLine: "I ordered a blue jacket but I received a red one. This isn't what I paid for.",
  },
  {
    id: 'rp-7',
    difficulty: 'Intermediate',
    category: 'Retention',
    title: 'Requesting a plan change',
    context: 'A customer wants to switch to a cheaper plan.',
    objective: 'Explain the options clearly without being pushy.',
    customerPersona: 'Practical, budget-conscious.',
    problem: 'Current plan is too expensive for their needs.',
    availableInfo: ['Basic plan is $10 cheaper but has fewer features', 'Change takes effect next billing cycle'],
    expectedResolution: 'Explain the trade-offs clearly and process the change if they confirm.',
    openingLine: 'I want to downgrade my plan, it\'s too expensive. What are my options?',
  },

  // ------------------------------------------------------------- Advanced ---
  {
    id: 'rp-8',
    difficulty: 'Advanced',
    category: 'Technical Support',
    title: 'Angry about a service outage',
    context: 'A customer lost internet access during a work call and is upset.',
    objective: 'De-escalate and offer a fair resolution.',
    customerPersona: 'Angry, raises their voice, wants compensation.',
    problem: 'Service was down for 3 hours during an important meeting.',
    availableInfo: ['Outage was due to regional maintenance', 'Compensation policy allows a partial refund for outages over 2 hours'],
    expectedResolution: 'Acknowledge the frustration, explain the cause honestly, and offer the partial refund.',
    openingLine: "This is unacceptable! I lost internet for THREE HOURS during an important work call. I want compensation NOW.",
  },
  {
    id: 'rp-9',
    difficulty: 'Advanced',
    category: 'Sales',
    title: 'Demanding an unauthorized discount',
    context: 'A customer insists on a discount that isn\'t available.',
    objective: 'Hold the policy professionally while staying helpful.',
    customerPersona: 'Pushy, repeats the same demand.',
    problem: 'Wants a 50% discount that doesn\'t exist.',
    availableInfo: ['Current promotion is 10% off', 'No exceptions can be made without manager approval'],
    expectedResolution: 'Politely explain what is actually available, and offer to escalate if they insist.',
    openingLine: "I know you can give me 50% off, other companies do it. Just do it, I'm a loyal customer!",
  },
  {
    id: 'rp-10',
    difficulty: 'Advanced',
    category: 'Retention',
    title: 'Threatening to leave a bad review',
    context: 'A customer is upset about a minor delay and threatens to post negative reviews.',
    objective: 'Stay calm and professional without over-promising.',
    customerPersona: 'Frustrated, uses the threat as leverage.',
    problem: 'A 1-day delivery delay.',
    availableInfo: ['Delay was due to high order volume', 'Order will arrive tomorrow'],
    expectedResolution: 'Apologize sincerely, explain the situation, and reassure them without making promises you can\'t keep.',
    openingLine: "If my order isn't here by tomorrow, I'm posting a 1-star review everywhere. This is ridiculous.",
  },

  // --------------------------------------------------------------- Expert ---
  {
    id: 'rp-11',
    difficulty: 'Expert',
    category: 'Escalation',
    title: 'Aggressive customer demanding a supervisor',
    context: 'A very upset customer refuses to talk to anyone but a manager, using harsh language.',
    objective: 'Stay professional, de-escalate, and manage the escalation properly.',
    customerPersona: 'Aggressive, interrupts, raises voice, demands immediate escalation.',
    problem: 'Billed twice for the same service and feels ignored by two previous agents.',
    availableInfo: ['Double charge is visible in the system', 'Refund can be processed within 24-48 hours', 'Supervisor is available for escalation'],
    expectedResolution: 'Acknowledge the repeated frustration, verify the double charge, offer to process the refund yourself, and still offer escalation if they insist.',
    openingLine: "I've called TWICE already and NOBODY has fixed this! Get me your manager RIGHT NOW, I'm done talking to agents who can't help me!",
  },
  {
    id: 'rp-12',
    difficulty: 'Expert',
    category: 'Escalation',
    title: 'Complex multi-issue complaint',
    context: 'A customer has several unrelated problems and is overwhelmed and upset.',
    objective: 'Organize the issues, address them one at a time, and keep control of the conversation.',
    customerPersona: 'Overwhelmed, jumps between topics, emotional.',
    problem: 'Wrong item received, a billing error, AND a cancelled appointment — all in the same week.',
    availableInfo: ['Wrong item: free return + replacement available', 'Billing error: refund can be issued', 'Appointment: can be rescheduled this week'],
    expectedResolution: 'Calmly organize the three issues, confirm each one, and resolve or schedule a resolution for all three.',
    openingLine: "I don't even know where to start. I got the wrong item, you overcharged me, AND you cancelled my appointment without telling me. What is going on?!",
  },

  // ---------------------------------------------------------- Cancellation & Sales ---
  {
    id: 'rp-13',
    difficulty: 'Intermediate',
    category: 'Cancellation',
    title: 'Customer wants to cancel',
    context: 'A customer wants to cancel their subscription entirely.',
    objective: 'Understand why, offer alternatives, and process the cancellation respectfully if they insist.',
    customerPersona: 'Decided, a bit impatient, doesn\'t want to be talked out of it.',
    problem: 'Feels the service is no longer worth the cost.',
    availableInfo: ['A 20% loyalty discount is available for 3 months', 'Cancellation takes effect at the end of the billing cycle', 'No cancellation fee'],
    expectedResolution: 'Ask the reason, offer the loyalty discount once, and process the cancellation without pressure if declined.',
    openingLine: "I'd like to cancel my subscription, please. I've already made up my mind.",
  },
  {
    id: 'rp-14',
    difficulty: 'Beginner',
    category: 'Sales',
    title: 'Customer asks about a product',
    context: 'A potential customer is asking about a premium plan before buying.',
    objective: 'Answer clearly and highlight the value without being pushy.',
    customerPersona: 'Curious, comparing options, hasn\'t decided yet.',
    problem: 'Not sure if the premium plan is worth the extra cost.',
    availableInfo: ['Premium plan includes priority support and no ads', 'Free 14-day trial available', 'Can downgrade anytime'],
    expectedResolution: 'Explain the premium benefits clearly and offer the free trial.',
    openingLine: "Hi, I'm looking at your premium plan — what extra do I actually get for the higher price?",
  },
];
