import { CallCenterVocabularyWord } from '../../models';

export const MOCK_INTERVIEW_VOCABULARY: CallCenterVocabularyWord[] = [
  // ---------------------------------------------------------- Customer Service ---
  { id: 'cc-customer', term: 'Customer', translation: 'Cliente', pronunciation: '/ˈkʌs.tə.mɚ/', example: 'The customer called about a billing issue.', category: 'Customer Service', difficulty: 'easy' },
  { id: 'cc-representative', term: 'Representative', translation: 'Representante', pronunciation: '/ˌrep.rɪˈzen.tə.tɪv/', example: "I'll connect you with a representative.", category: 'Customer Service', difficulty: 'medium' },
  { id: 'cc-issue', term: 'Issue', translation: 'Problema / inconveniente', pronunciation: '/ˈɪʃ.uː/', example: 'What issue are you experiencing today?', category: 'Customer Service', difficulty: 'easy' },
  { id: 'cc-complaint', term: 'Complaint', translation: 'Queja', pronunciation: '/kəmˈpleɪnt/', example: 'She filed a complaint about the delay.', category: 'Customer Service', difficulty: 'medium' },
  { id: 'cc-request', term: 'Request', translation: 'Solicitud', pronunciation: '/rɪˈkwest/', example: 'I received your request for a refund.', category: 'Customer Service', difficulty: 'easy' },
  { id: 'cc-solution', term: 'Solution', translation: 'Solución', pronunciation: '/səˈluː.ʃən/', example: "Let's find a solution together.", category: 'Customer Service', difficulty: 'easy' },
  { id: 'cc-assistance', term: 'Assistance', translation: 'Asistencia / ayuda', pronunciation: '/əˈsɪs.təns/', example: 'How may I offer you assistance today?', category: 'Customer Service', difficulty: 'medium' },
  { id: 'cc-feedback', term: 'Feedback', translation: 'Comentarios / retroalimentación', pronunciation: '/ˈfiːd.bæk/', example: 'We appreciate your feedback.', category: 'Customer Service', difficulty: 'medium' },
  { id: 'cc-satisfaction', term: 'Satisfaction', translation: 'Satisfacción', pronunciation: '/ˌsæt.ɪsˈfæk.ʃən/', example: 'Customer satisfaction is our top priority.', category: 'Customer Service', difficulty: 'hard' },
  { id: 'cc-inconvenience', term: 'Inconvenience', translation: 'Molestia / inconveniente', pronunciation: '/ˌɪn.kənˈviː.ni.əns/', example: "I'm sorry for the inconvenience.", category: 'Customer Service', difficulty: 'hard' },
  { id: 'cc-loyal', term: 'Loyal customer', translation: 'Cliente fiel', pronunciation: '/ˈlɔɪ.əl/', example: 'She has been a loyal customer for years.', category: 'Customer Service', difficulty: 'medium' },
  { id: 'cc-refund', term: 'Refund', translation: 'Reembolso', pronunciation: '/ˈriː.fʌnd/', example: 'We processed your refund today.', category: 'Customer Service', difficulty: 'easy' },
  { id: 'cc-account', term: 'Account', translation: 'Cuenta', pronunciation: '/əˈkaʊnt/', example: 'Can you confirm your account number?', category: 'Customer Service', difficulty: 'easy' },
  { id: 'cc-billing', term: 'Billing', translation: 'Facturación', pronunciation: '/ˈbɪl.ɪŋ/', example: 'I have a question about my billing.', category: 'Customer Service', difficulty: 'medium' },

  // -------------------------------------------------------------------- Calls ---
  { id: 'cc-hold', term: 'Hold', translation: 'Espera (en llamada)', pronunciation: '/hoʊld/', example: 'Would you mind holding for a moment?', category: 'Calls', difficulty: 'easy' },
  { id: 'cc-transfer', term: 'Transfer', translation: 'Transferir', pronunciation: '/trænsˈfɝː/', example: "I'll transfer you to billing.", category: 'Calls', difficulty: 'easy' },
  { id: 'cc-disconnect', term: 'Disconnect', translation: 'Cortarse (la llamada)', pronunciation: '/ˌdɪs.kəˈnekt/', example: 'The call disconnected suddenly.', category: 'Calls', difficulty: 'medium' },
  { id: 'cc-call-back', term: 'Call back', translation: 'Devolver la llamada', pronunciation: '/kɔːl bæk/', example: "I'll call you back in five minutes.", category: 'Calls', difficulty: 'easy' },
  { id: 'cc-line', term: 'Line', translation: 'Línea', pronunciation: '/laɪn/', example: 'Please stay on the line.', category: 'Calls', difficulty: 'easy' },
  { id: 'cc-connection', term: 'Connection', translation: 'Conexión', pronunciation: '/kəˈnek.ʃən/', example: 'The connection is a bit unstable.', category: 'Calls', difficulty: 'medium' },
  { id: 'cc-mute', term: 'Mute', translation: 'Silenciar', pronunciation: '/mjuːt/', example: 'Sorry, you were on mute.', category: 'Calls', difficulty: 'easy' },
  { id: 'cc-volume', term: 'Volume', translation: 'Volumen', pronunciation: '/ˈvɑːl.juːm/', example: 'Could you increase the volume, please?', category: 'Calls', difficulty: 'easy' },
  { id: 'cc-inbound', term: 'Inbound call', translation: 'Llamada entrante', pronunciation: '/ˈɪn.baʊnd/', example: 'We handle inbound calls all day.', category: 'Calls', difficulty: 'hard' },
  { id: 'cc-outbound', term: 'Outbound call', translation: 'Llamada saliente', pronunciation: '/ˈaʊt.baʊnd/', example: 'This team makes outbound calls to leads.', category: 'Calls', difficulty: 'hard' },
  { id: 'cc-script', term: 'Script', translation: 'Guion (de llamada)', pronunciation: '/skrɪpt/', example: 'New agents follow a script at first.', category: 'Calls', difficulty: 'medium' },
  { id: 'cc-queue', term: 'Queue', translation: 'Fila de espera', pronunciation: '/kjuː/', example: 'You are third in the queue.', category: 'Calls', difficulty: 'medium' },
  { id: 'cc-headset', term: 'Headset', translation: 'Auriculares con micrófono', pronunciation: '/ˈhed.set/', example: 'Please check your headset before the shift.', category: 'Calls', difficulty: 'medium' },
  { id: 'cc-wrap-up', term: 'Wrap-up time', translation: 'Tiempo para cerrar el caso', pronunciation: '/ræp ʌp/', example: 'I need a minute of wrap-up time.', category: 'Calls', difficulty: 'hard' },

  // ------------------------------------------------------------- Problem Solving ---
  { id: 'cc-resolve', term: 'Resolve', translation: 'Resolver', pronunciation: '/rɪˈzɑːlv/', example: "I'll resolve this for you right away.", category: 'Problem Solving', difficulty: 'medium' },
  { id: 'cc-troubleshoot', term: 'Troubleshoot', translation: 'Diagnosticar / solucionar problemas técnicos', pronunciation: '/ˈtrʌb.əl.ʃuːt/', example: "Let's troubleshoot the connection issue.", category: 'Problem Solving', difficulty: 'hard' },
  { id: 'cc-investigate', term: 'Investigate', translation: 'Investigar', pronunciation: '/ɪnˈves.tɪ.ɡeɪt/', example: "I'll investigate the charge on your account.", category: 'Problem Solving', difficulty: 'medium' },
  { id: 'cc-escalate', term: 'Escalate', translation: 'Escalar (a otro nivel)', pronunciation: '/ˈes.kə.leɪt/', example: 'I need to escalate this to my supervisor.', category: 'Problem Solving', difficulty: 'hard' },
  { id: 'cc-follow-up', term: 'Follow up', translation: 'Dar seguimiento', pronunciation: '/ˈfɑː.loʊ ʌp/', example: "I'll follow up with you tomorrow.", category: 'Problem Solving', difficulty: 'medium' },
  { id: 'cc-verify', term: 'Verify', translation: 'Verificar', pronunciation: '/ˈver.ə.faɪ/', example: 'Let me verify your information.', category: 'Problem Solving', difficulty: 'medium' },
  { id: 'cc-root-cause', term: 'Root cause', translation: 'Causa raíz', pronunciation: '/ruːt kɔːz/', example: 'We need to find the root cause.', category: 'Problem Solving', difficulty: 'hard' },
  { id: 'cc-workaround', term: 'Workaround', translation: 'Solución temporal', pronunciation: '/ˈwɝːk.əˌraʊnd/', example: "Here's a workaround while we fix it.", category: 'Problem Solving', difficulty: 'hard' },
  { id: 'cc-glitch-cc', term: 'Glitch', translation: 'Fallo técnico', pronunciation: '/ɡlɪtʃ/', example: 'It looks like a system glitch.', category: 'Problem Solving', difficulty: 'medium' },
  { id: 'cc-priority', term: 'Priority', translation: 'Prioridad', pronunciation: '/praɪˈɔːr.ə.ti/', example: 'This case is high priority.', category: 'Problem Solving', difficulty: 'medium' },
  { id: 'cc-update-record', term: 'Update the record', translation: 'Actualizar el registro', pronunciation: '/ʌpˈdeɪt/', example: "I'll update the record with your new address.", category: 'Problem Solving', difficulty: 'medium' },
  { id: 'cc-confirm', term: 'Confirm', translation: 'Confirmar', pronunciation: '/kənˈfɝːm/', example: 'Can you confirm your email address?', category: 'Problem Solving', difficulty: 'easy' },
  { id: 'cc-double-check', term: 'Double-check', translation: 'Verificar dos veces', pronunciation: '/ˈdʌb.əl tʃek/', example: 'Let me double-check that for you.', category: 'Problem Solving', difficulty: 'medium' },
  { id: 'cc-compensation', term: 'Compensation', translation: 'Compensación', pronunciation: '/ˌkɑːm.pənˈseɪ.ʃən/', example: 'We can offer compensation for the delay.', category: 'Problem Solving', difficulty: 'hard' },

  // -------------------------------------------------------------------- Sales ---
  { id: 'cc-purchase', term: 'Purchase', translation: 'Compra', pronunciation: '/ˈpɝː.tʃəs/', example: 'Thank you for your purchase.', category: 'Sales', difficulty: 'easy' },
  { id: 'cc-offer', term: 'Offer', translation: 'Oferta', pronunciation: '/ˈɔː.fɚ/', example: 'We have a special offer this month.', category: 'Sales', difficulty: 'easy' },
  { id: 'cc-discount', term: 'Discount', translation: 'Descuento', pronunciation: '/ˈdɪs.kaʊnt/', example: 'You qualify for a 10% discount.', category: 'Sales', difficulty: 'easy' },
  { id: 'cc-subscription', term: 'Subscription', translation: 'Suscripción', pronunciation: '/səbˈskrɪp.ʃən/', example: 'Your subscription renews next month.', category: 'Sales', difficulty: 'medium' },
  { id: 'cc-upgrade', term: 'Upgrade', translation: 'Mejorar / actualizar (plan)', pronunciation: '/ˈʌp.ɡreɪd/', example: 'Would you like to upgrade your plan?', category: 'Sales', difficulty: 'medium' },
  { id: 'cc-promotion', term: 'Promotion', translation: 'Promoción', pronunciation: '/prəˈmoʊ.ʃən/', example: "There's a promotion for new customers.", category: 'Sales', difficulty: 'medium' },
  { id: 'cc-quote', term: 'Quote', translation: 'Cotización', pronunciation: '/kwoʊt/', example: 'I can give you a quote for that plan.', category: 'Sales', difficulty: 'medium' },
  { id: 'cc-lead', term: 'Lead', translation: 'Cliente potencial', pronunciation: '/liːd/', example: 'This lead is interested in our service.', category: 'Sales', difficulty: 'hard' },
  { id: 'cc-close-a-deal', term: 'Close a deal', translation: 'Cerrar una venta', pronunciation: '/kloʊz ə diːl/', example: 'We closed the deal yesterday.', category: 'Sales', difficulty: 'hard' },
  { id: 'cc-renewal', term: 'Renewal', translation: 'Renovación', pronunciation: '/rɪˈnuː.əl/', example: 'Your renewal date is in March.', category: 'Sales', difficulty: 'hard' },
  { id: 'cc-plan', term: 'Plan', translation: 'Plan (de servicio)', pronunciation: '/plæn/', example: 'Which plan fits you best?', category: 'Sales', difficulty: 'easy' },
  { id: 'cc-cancel', term: 'Cancel', translation: 'Cancelar', pronunciation: '/ˈkæn.səl/', example: "I understand you'd like to cancel your service.", category: 'Sales', difficulty: 'easy' },
  { id: 'cc-value', term: 'Value', translation: 'Valor', pronunciation: '/ˈvæl.juː/', example: 'This plan gives you the best value.', category: 'Sales', difficulty: 'medium' },
];
