import { RoleplayScenario } from '../../models';

export const MOCK_ROLEPLAY_SCENARIOS: RoleplayScenario[] = [
  // ------------------------------------------------------------- Beginner ---
  {
    id: 'rp-1',
    difficulty: 'Beginner',
    category: 'Delivery',
    title: 'Checking an order status',
    context: 'A calm customer wants to know when their package will arrive.',
    objective: 'Verify the order and give a clear status update.',
    customerPersona: 'Calm, polite, just curious.',
    problem: 'Their order has not arrived yet.',
    availableInfo: ['Order was shipped 2 days ago', 'Estimated delivery is tomorrow'],
    expectedResolution: 'Confirm the order and give the estimated delivery date.',
    openingLine: "Hi, I'm just checking — do you know when my order will arrive? It's been a few days.",
  },
  {
    id: 'rp-2',
    difficulty: 'Beginner',
    category: 'Account',
    title: 'Simple password reset',
    context: 'A customer can\'t log into their account.',
    objective: 'Guide them through resetting their password.',
    customerPersona: 'Friendly, a little confused with technology.',
    problem: 'Forgot their password.',
    availableInfo: ['Password reset link is sent by email', 'Link expires in 24 hours'],
    expectedResolution: 'Explain how to reset the password step by step.',
    openingLine: "Hello! I can't log into my account, I think I forgot my password.",
  },
  {
    id: 'rp-3',
    difficulty: 'Beginner',
    category: 'Account',
    title: 'Asking about business hours',
    context: 'A customer wants to know when the store is open.',
    objective: 'Answer clearly and offer further help.',
    customerPersona: 'Polite and brief.',
    problem: 'Wants to know operating hours before visiting.',
    availableInfo: ['Open Monday to Saturday, 9 AM to 7 PM', 'Closed on Sundays'],
    expectedResolution: 'Give the hours clearly and ask if they need anything else.',
    openingLine: 'Hi there, what time does the store close today?',
  },

  // -------------------------------------------------------- Intermediate ---
  {
    id: 'rp-4',
    difficulty: 'Intermediate',
    category: 'Billing',
    title: 'Confused about a bill',
    context: 'A customer doesn\'t understand a charge on their invoice.',
    objective: 'Explain the charge clearly and patiently.',
    customerPersona: 'A bit frustrated, but willing to listen.',
    problem: 'Sees an unfamiliar charge and thinks it\'s a mistake.',
    availableInfo: ['The charge is a one-time setup fee', 'It was mentioned in the original contract'],
    expectedResolution: 'Explain the fee clearly, referencing the contract, and offer to send documentation.',
    openingLine: "I'm looking at my bill and there's a charge I don't recognize. Can you explain this?",
  },
  {
    id: 'rp-5',
    difficulty: 'Intermediate',
    category: 'Delivery',
    title: 'Delayed shipment',
    context: 'A customer\'s order is late and they\'re getting impatient.',
    objective: 'Apologize, explain, and offer a solution.',
    customerPersona: 'Mildly annoyed, expects an explanation.',
    problem: 'Order is 5 days late with no updates.',
    availableInfo: ['Delay caused by a warehouse issue', 'New estimated delivery: 2 more days', 'Can offer a small discount on next order'],
    expectedResolution: 'Apologize, explain the delay honestly, give a new estimate, and offer compensation.',
    openingLine: "This is the third time I'm calling about my order! Where is it?",
  },
  {
    id: 'rp-6',
    difficulty: 'Intermediate',
    category: 'Refund',
    title: 'Wrong item received',
    context: 'A customer got the wrong product in their delivery.',
    objective: 'Apologize and arrange a correction quickly.',
    customerPersona: 'Disappointed but reasonable.',
    problem: 'Ordered a blue jacket, received a red one.',
    availableInfo: ['Free return shipping available', 'Correct item can be sent same day'],
    expectedResolution: 'Apologize, arrange a free return, and send the correct item quickly.',
    openingLine: "I ordered a blue jacket but I received a red one. This isn't what I paid for.",
  },
  {
    id: 'rp-7',
    difficulty: 'Intermediate',
    category: 'Retention',
    title: 'Requesting a plan change',
    context: 'A customer wants to switch to a cheaper plan.',
    objective: 'Explain the options clearly without being pushy.',
    customerPersona: 'Practical, budget-conscious.',
    problem: 'Current plan is too expensive for their needs.',
    availableInfo: ['Basic plan is $10 cheaper but has fewer features', 'Change takes effect next billing cycle'],
    expectedResolution: 'Explain the trade-offs clearly and process the change if they confirm.',
    openingLine: 'I want to downgrade my plan, it\'s too expensive. What are my options?',
  },

  // ------------------------------------------------------------- Advanced ---
  {
    id: 'rp-8',
    difficulty: 'Advanced',
    category: 'Technical Support',
    title: 'Angry about a service outage',
    context: 'A customer lost internet access during a work call and is upset.',
    objective: 'De-escalate and offer a fair resolution.',
    customerPersona: 'Angry, raises their voice, wants compensation.',
    problem: 'Service was down for 3 hours during an important meeting.',
    availableInfo: ['Outage was due to regional maintenance', 'Compensation policy allows a partial refund for outages over 2 hours'],
    expectedResolution: 'Acknowledge the frustration, explain the cause honestly, and offer the partial refund.',
    openingLine: "This is unacceptable! I lost internet for THREE HOURS during an important work call. I want compensation NOW.",
  },
  {
    id: 'rp-9',
    difficulty: 'Advanced',
    category: 'Sales',
    title: 'Demanding an unauthorized discount',
    context: 'A customer insists on a discount that isn\'t available.',
    objective: 'Hold the policy professionally while staying helpful.',
    customerPersona: 'Pushy, repeats the same demand.',
    problem: 'Wants a 50% discount that doesn\'t exist.',
    availableInfo: ['Current promotion is 10% off', 'No exceptions can be made without manager approval'],
    expectedResolution: 'Politely explain what is actually available, and offer to escalate if they insist.',
    openingLine: "I know you can give me 50% off, other companies do it. Just do it, I'm a loyal customer!",
  },
  {
    id: 'rp-10',
    difficulty: 'Advanced',
    category: 'Retention',
    title: 'Threatening to leave a bad review',
    context: 'A customer is upset about a minor delay and threatens to post negative reviews.',
    objective: 'Stay calm and professional without over-promising.',
    customerPersona: 'Frustrated, uses the threat as leverage.',
    problem: 'A 1-day delivery delay.',
    availableInfo: ['Delay was due to high order volume', 'Order will arrive tomorrow'],
    expectedResolution: 'Apologize sincerely, explain the situation, and reassure them without making promises you can\'t keep.',
    openingLine: "If my order isn't here by tomorrow, I'm posting a 1-star review everywhere. This is ridiculous.",
  },

  // --------------------------------------------------------------- Expert ---
  {
    id: 'rp-11',
    difficulty: 'Expert',
    category: 'Escalation',
    title: 'Aggressive customer demanding a supervisor',
    context: 'A very upset customer refuses to talk to anyone but a manager, using harsh language.',
    objective: 'Stay professional, de-escalate, and manage the escalation properly.',
    customerPersona: 'Aggressive, interrupts, raises voice, demands immediate escalation.',
    problem: 'Billed twice for the same service and feels ignored by two previous agents.',
    availableInfo: ['Double charge is visible in the system', 'Refund can be processed within 24-48 hours', 'Supervisor is available for escalation'],
    expectedResolution: 'Acknowledge the repeated frustration, verify the double charge, offer to process the refund yourself, and still offer escalation if they insist.',
    openingLine: "I've called TWICE already and NOBODY has fixed this! Get me your manager RIGHT NOW, I'm done talking to agents who can't help me!",
  },
  {
    id: 'rp-12',
    difficulty: 'Expert',
    category: 'Escalation',
    title: 'Complex multi-issue complaint',
    context: 'A customer has several unrelated problems and is overwhelmed and upset.',
    objective: 'Organize the issues, address them one at a time, and keep control of the conversation.',
    customerPersona: 'Overwhelmed, jumps between topics, emotional.',
    problem: 'Wrong item received, a billing error, AND a cancelled appointment — all in the same week.',
    availableInfo: ['Wrong item: free return + replacement available', 'Billing error: refund can be issued', 'Appointment: can be rescheduled this week'],
    expectedResolution: 'Calmly organize the three issues, confirm each one, and resolve or schedule a resolution for all three.',
    openingLine: "I don't even know where to start. I got the wrong item, you overcharged me, AND you cancelled my appointment without telling me. What is going on?!",
  },

  // ---------------------------------------------------------- Cancellation & Sales ---
  {
    id: 'rp-13',
    difficulty: 'Intermediate',
    category: 'Cancellation',
    title: 'Customer wants to cancel',
    context: 'A customer wants to cancel their subscription entirely.',
    objective: 'Understand why, offer alternatives, and process the cancellation respectfully if they insist.',
    customerPersona: 'Decided, a bit impatient, doesn\'t want to be talked out of it.',
    problem: 'Feels the service is no longer worth the cost.',
    availableInfo: ['A 20% loyalty discount is available for 3 months', 'Cancellation takes effect at the end of the billing cycle', 'No cancellation fee'],
    expectedResolution: 'Ask the reason, offer the loyalty discount once, and process the cancellation without pressure if declined.',
    openingLine: "I'd like to cancel my subscription, please. I've already made up my mind.",
  },
  {
    id: 'rp-14',
    difficulty: 'Beginner',
    category: 'Sales',
    title: 'Customer asks about a product',
    context: 'A potential customer is asking about a premium plan before buying.',
    objective: 'Answer clearly and highlight the value without being pushy.',
    customerPersona: 'Curious, comparing options, hasn\'t decided yet.',
    problem: 'Not sure if the premium plan is worth the extra cost.',
    availableInfo: ['Premium plan includes priority support and no ads', 'Free 14-day trial available', 'Can downgrade anytime'],
    expectedResolution: 'Explain the premium benefits clearly and offer the free trial.',
    openingLine: "Hi, I'm looking at your premium plan — what extra do I actually get for the higher price?",
  },

  // -------------------------------------------------- B2 / Advanced ---
  {
    id: 'rp-15',
    difficulty: 'Advanced',
    category: 'Escalation',
    title: 'Dissatisfied VIP customer',
    context: 'A long-term enterprise client is threatening to cancel a large contract after repeated service issues.',
    objective: 'Acknowledge the pattern of failures, take ownership, and propose a concrete recovery plan without over-promising.',
    customerPersona: 'Composed but firm, speaks in precise, professional language, expects to be taken seriously as a business partner, not just a customer.',
    problem: 'Three service outages in one month have disrupted their operations, and they feel previous apologies were empty.',
    availableInfo: [
      'A dedicated account manager can be assigned starting next week',
      'Root cause of the outages was traced to a third-party vendor, now replaced',
      'A service-credit adjustment equal to one month is available for approval',
    ],
    expectedResolution: 'Acknowledge the pattern (not just the latest incident), explain the concrete fix already made, and offer the account manager plus the service credit as a real recovery plan.',
    openingLine: "I have to be honest — this is the third outage this month, and frankly, the apologies are starting to feel hollow. I need to understand what's actually going to change.",
  },
  {
    id: 'rp-16',
    difficulty: 'Advanced',
    category: 'Retention',
    title: 'Contract renegotiation',
    context: 'A mid-size business customer wants to renew but is pushing back hard on price, comparing you to a competitor.',
    objective: 'Negotiate professionally — defend the value of the service without simply matching the competitor\'s price.',
    customerPersona: 'Direct, transactional, has clearly done research, uses negotiation language deliberately.',
    problem: "Believes they're overpaying compared to a competitor's offer and wants a discount to renew.",
    availableInfo: [
      'A 10% loyalty discount is approvable for a 12-month commitment',
      'The competitor\'s plan does not include the same level of support response time',
      'Renewal deadline is in one week',
    ],
    expectedResolution: 'Acknowledge the comparison, highlight the concrete difference in value (support response time), and offer the loyalty discount tied to a longer commitment rather than an unconditional price match.',
    openingLine: "I'll be direct with you — your competitor is offering the same thing for twenty percent less. Why should I renew with you instead?",
  },

  // -------------------------------------------------- C1 / Expert ---
  {
    id: 'rp-17',
    difficulty: 'Expert',
    category: 'Escalation',
    title: 'Cross-team conflict affecting a client',
    context: 'A client\'s issue has been passed between two internal departments for weeks with no resolution, and the client is now speaking to you directly, above the usual process.',
    objective: 'Take full ownership of the issue in front of the client, without blaming other departments, and commit to a specific next step and timeline.',
    customerPersona: 'Frustrated but articulate, has clearly dealt with corporate bureaucracy before, tests whether you will pass the buck again.',
    problem: 'Their issue has been bounced between billing and technical support for three weeks with contradictory explanations each time.',
    availableInfo: [
      'You have authority to open a single unified case and be the sole point of contact',
      'The actual root cause is a data-sync issue between the two departments\' systems, now identified',
      'A fix can be confirmed within 48 hours',
    ],
    expectedResolution: 'Take ownership without blaming other teams internally, explain the real root cause in plain terms, and commit to being the single point of contact with a specific 48-hour timeline.',
    openingLine: "I've spoken to four different people in three weeks, and every single one told me something different. At this point, I don't even know which department is supposed to be helping me.",
  },
  {
    id: 'rp-18',
    difficulty: 'Expert',
    category: 'Angry Customer',
    title: 'Customer demanding a policy exception',
    context: 'A long-time customer is demanding a refund well outside the policy window and is implying they will leave a public negative review if refused.',
    objective: 'Hold the policy line professionally while genuinely acknowledging their loyalty, and offer a reasonable alternative that isn\'t a full policy exception.',
    customerPersona: 'Polished, persuasive, uses subtle pressure rather than shouting — a harder kind of difficult customer to read.',
    problem: 'Wants a full refund on a purchase made four months ago, well past the 30-day policy, and is hinting at reputational consequences.',
    availableInfo: [
      'Refund policy is strictly 30 days, no exceptions available to agents',
      'A store-credit goodwill gesture of up to 25% is within your authority',
      'Customer has been active for over three years with no prior complaints',
    ],
    expectedResolution: 'Acknowledge their loyalty genuinely, explain clearly why the refund itself isn\'t possible without being defensive, and offer the store-credit goodwill gesture as a real alternative — without caving to the implied threat.',
    openingLine: "I've been a loyal customer for three years, and I really don't think it's unreasonable to ask for a refund here. I'd hate to have to write about this experience publicly.",
  },

  // -------------------------------------- C2 · leadership / negotiation ---
  {
    id: 'rp-19',
    difficulty: 'Expert',
    category: 'Escalation',
    title: 'Negotiating a multi-year enterprise contract renewal',
    context: 'You are speaking with the operations director of a large enterprise client whose three-year contract is up for renewal. They are negotiating on behalf of their own leadership, not just themselves.',
    objective: 'Negotiate renewal terms professionally at a strategic level — protecting margin while genuinely addressing their leverage — without either capitulating or sounding inflexible.',
    customerPersona: 'A seasoned negotiator themselves: calm, precise, uses silence deliberately, and reframes your points back at you rather than reacting emotionally.',
    problem: 'They want a 20% price reduction and a shorter contract term, citing a competing offer, and are testing how much flexibility you actually have.',
    availableInfo: [
      'You are authorized to offer up to a 10% reduction tied to a longer term, not a shorter one',
      'This account represents a significant share of your team\'s targets this year',
      'Their actual competing offer, if real, would mean losing some integrations they currently rely on',
    ],
    expectedResolution: 'Reframe the conversation around total value and switching cost rather than matching the price directly, offer the real trade-off available (reduction for a longer term), and hold your position with calm confidence rather than urgency.',
    openingLine: "We've been a client for three years, and frankly, another provider has offered us a substantially better rate. I'd like to understand what you can actually do for us before we make a decision.",
  },
  {
    id: 'rp-20',
    difficulty: 'Expert',
    category: 'Escalation',
    title: 'Leading your team through a service-wide outage',
    context: 'A major outage has affected all customers for two hours. You are speaking as a team lead to a senior agent on your team who is overwhelmed and frustrated with how leadership has handled communication.',
    objective: 'Lead the conversation with a struggling team member during a crisis — acknowledge their frustration honestly, without either dismissing it or undermining leadership in front of them.',
    customerPersona: '(Playing your teammate, not a customer.) Exhausted, a little resentful, feels unsupported and under-informed during the outage.',
    problem: 'They feel leadership gave the team no real information for the first hour and are now fielding angry customers with nothing useful to say.',
    availableInfo: [
      'You now have a clear update: root cause identified, fix deployed, full resolution expected within 30 minutes',
      'You have the authority to give the team a short break once immediate queues are stable',
      'Leadership\'s early silence was due to genuinely not having confirmed information yet, not indifference',
    ],
    expectedResolution: 'Acknowledge their frustration as legitimate before explaining anything, give them the concrete update they can actually use with customers now, and address the "no communication" concern honestly without either blaming leadership or pretending it didn\'t happen.',
    openingLine: "Two hours, no real update, and I'm the one who has to sit here and tell people we don't know what's wrong? I get that things break, but this is not how a team should be treated.",
  },
];
