import { ExerciseType, SpeakingExercise } from '../../models';

export const MOCK_SPEAKING_EXERCISES: SpeakingExercise[] = [
  {
    id: 'sp-1',
    type: ExerciseType.Speaking,
    prompt: 'Practice this everyday sentence.',
    expectedSentence: 'I went to the supermarket yesterday.',
    hint: 'Past tense: "went", not "go".',
    xpReward: 15,
  },
  {
    id: 'sp-2',
    type: ExerciseType.Speaking,
    prompt: 'Practice introducing yourself.',
    expectedSentence: 'My name is Andres and I am learning English.',
    xpReward: 15,
  },
  {
    id: 'sp-3',
    type: ExerciseType.Speaking,
    prompt: 'Practice asking for help politely.',
    expectedSentence: 'Excuse me, could you help me find the train station?',
    hint: '"Could you" is a polite way to ask.',
    xpReward: 15,
  },
  {
    id: 'sp-4',
    type: ExerciseType.Speaking,
    prompt: 'Practice talking about plans.',
    expectedSentence: "I'm going to visit my family this weekend.",
    xpReward: 15,
  },
  {
    id: 'sp-5',
    type: ExerciseType.Speaking,
    prompt: 'Practice ordering food at a restaurant.',
    expectedSentence: "I'd like the grilled chicken with a side salad, please.",
    hint: '"I\'d like" is more polite than "I want".',
    xpReward: 15,
  },
  {
    id: 'sp-6',
    type: ExerciseType.Speaking,
    prompt: 'Practice describing your job.',
    expectedSentence: 'I work as a customer service representative for a technology company.',
    xpReward: 16,
  },
  {
    id: 'sp-7',
    type: ExerciseType.Speaking,
    prompt: 'Practice giving directions.',
    expectedSentence: 'Go straight ahead and turn left at the second traffic light.',
    xpReward: 16,
  },
  {
    id: 'sp-8',
    type: ExerciseType.Speaking,
    prompt: 'Practice talking about your hobbies.',
    expectedSentence: 'In my free time, I enjoy reading books and playing the guitar.',
    xpReward: 16,
  },
  {
    id: 'sp-9',
    type: ExerciseType.Speaking,
    prompt: 'Practice apologizing for being late.',
    expectedSentence: "I'm sorry I'm late, the traffic was terrible this morning.",
    hint: 'Use "I\'m sorry" followed by a reason.',
    xpReward: 16,
  },
  {
    id: 'sp-10',
    type: ExerciseType.Speaking,
    prompt: 'Practice expressing an opinion.',
    expectedSentence: 'In my opinion, remote work improves productivity for most people.',
    xpReward: 17,
  },
  {
    id: 'sp-11',
    type: ExerciseType.Speaking,
    prompt: 'Practice making a suggestion.',
    expectedSentence: 'Why don\'t we reschedule the meeting for tomorrow afternoon?',
    hint: '"Why don\'t we..." is a common way to suggest.',
    xpReward: 17,
  },
  {
    id: 'sp-12',
    type: ExerciseType.Speaking,
    prompt: 'Practice describing a problem.',
    expectedSentence: "The application keeps crashing whenever I try to save my changes.",
    xpReward: 17,
  },
  {
    id: 'sp-13',
    type: ExerciseType.Speaking,
    prompt: 'Practice talking about future goals.',
    expectedSentence: 'By next year, I will have completed my professional certification.',
    hint: 'Future perfect: "will have + past participle".',
    xpReward: 18,
  },
  {
    id: 'sp-14',
    type: ExerciseType.Speaking,
    prompt: 'Practice comparing two options.',
    expectedSentence: 'Working from home is more flexible than commuting to an office every day.',
    xpReward: 18,
  },
  {
    id: 'sp-15',
    type: ExerciseType.Speaking,
    prompt: 'Practice handling a complaint.',
    expectedSentence: "I completely understand your frustration, and I'll do my best to resolve it right away.",
    xpReward: 19,
  },
  {
    id: 'sp-16',
    type: ExerciseType.Speaking,
    prompt: 'Practice a formal introduction in a meeting.',
    expectedSentence: 'Good morning everyone, thank you for joining the call on such short notice.',
    xpReward: 19,
  },
];
