import { ExerciseType, ListeningExercise } from '../../models';

export const MOCK_LISTENING_EXERCISES: ListeningExercise[] = [
  {
    id: 'li-1',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'Can you pass me the salt, please?',
    options: [
      'Can you pass me the salt, please?',
      'Can you pass me the sauce, please?',
      'Can you pass me the salad, please?',
    ],
    correctOptionIndex: 0,
    xpReward: 10,
  },
  {
    id: 'li-2',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'She has already finished her project.',
    options: [
      'She already finishes her project.',
      'She has already finished her project.',
      'She had finished her project already.',
    ],
    correctOptionIndex: 1,
    xpReward: 10,
  },
  {
    id: 'li-3',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'The meeting was moved to next Friday.',
    options: [
      'The meeting was moved to next Friday.',
      'The meeting was moved to last Friday.',
      'The meeting was removed on Friday.',
    ],
    correctOptionIndex: 0,
    xpReward: 10,
  },
  {
    id: 'li-4',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: "I haven't decided what to wear yet.",
    options: [
      "I haven't decided what to where yet.",
      "I haven't decided what to wear yet.",
      "I didn't decide what to wear yet.",
    ],
    correctOptionIndex: 1,
    xpReward: 10,
  },
  {
    id: 'li-5',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'They are planning to travel next summer.',
    options: [
      'They are planning to travel this summer.',
      'They were planning to travel next summer.',
      'They are planning to travel next summer.',
    ],
    correctOptionIndex: 2,
    xpReward: 10,
  },
  {
    id: 'li-6',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'Could you turn down the volume, please?',
    options: [
      'Could you turn down the volume, please?',
      'Could you turn up the volume, please?',
      'Could you turn off the volume, please?',
    ],
    correctOptionIndex: 0,
    xpReward: 10,
  },
  {
    id: 'li-7',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'We should leave before it starts raining.',
    options: [
      'We should leave before it starts raining.',
      'We should leave after it starts raining.',
      'We should leave before it stops raining.',
    ],
    correctOptionIndex: 0,
    xpReward: 10,
  },
  {
    id: 'li-8',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'He usually wakes up around seven o\'clock.',
    options: [
      'He usually wakes up around seven o\'clock.',
      'He usually wakes up around eleven o\'clock.',
      'He usually woke up around seven o\'clock.',
    ],
    correctOptionIndex: 0,
    xpReward: 10,
  },
  {
    id: 'li-9',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: "I'm afraid we don't have that item in stock right now.",
    options: [
      "I'm afraid we don't have that item in stock right now.",
      "I'm afraid we do have that item in stock right now.",
      "I'm afraid we won't have that item in stock right now.",
    ],
    correctOptionIndex: 0,
    xpReward: 12,
  },
  {
    id: 'li-10',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'If I were you, I would double-check the address first.',
    options: [
      'If I were you, I would double-check the address first.',
      'If I was you, I will double-check the address first.',
      'If I were you, I double-checked the address first.',
    ],
    correctOptionIndex: 0,
    xpReward: 12,
  },
  {
    id: 'li-11',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'By the time we arrived, the show had already started.',
    options: [
      'By the time we arrived, the show has already started.',
      'By the time we arrived, the show had already started.',
      'By the time we arrive, the show had already started.',
    ],
    correctOptionIndex: 1,
    xpReward: 12,
  },
  {
    id: 'li-12',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'Neither of the two options seems ideal to me.',
    options: [
      'Either of the two options seems ideal to me.',
      'None of the two options seem ideal to me.',
      'Neither of the two options seems ideal to me.',
    ],
    correctOptionIndex: 2,
    xpReward: 14,
  },
  {
    id: 'li-13',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'The report needs to be submitted by the end of the day.',
    options: [
      'The report needs to be submitted by the end of the day.',
      'The report needed to be submitted by the end of the day.',
      'The report needs to be submitted at the end of the week.',
    ],
    correctOptionIndex: 0,
    xpReward: 12,
  },
  {
    id: 'li-14',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'Despite the rain, the event went ahead as planned.',
    options: [
      'Despite the rain, the event went ahead as planned.',
      'Because of the rain, the event went ahead as planned.',
      'Despite the rain, the event was cancelled as planned.',
    ],
    correctOptionIndex: 0,
    xpReward: 14,
  },
  {
    id: 'li-15',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: "You'd better bring an umbrella, just in case.",
    options: [
      "You better bring an umbrella, just in case.",
      "You'd better bring an umbrella, just in case.",
      "You'd rather bring an umbrella, just in case.",
    ],
    correctOptionIndex: 1,
    xpReward: 12,
  },
  {
    id: 'li-16',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'I used to live in a small town before I moved here.',
    options: [
      'I use to live in a small town before I moved here.',
      'I used to living in a small town before I moved here.',
      'I used to live in a small town before I moved here.',
    ],
    correctOptionIndex: 2,
    xpReward: 12,
  },
  {
    id: 'li-17',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: "Whoever finishes first can leave early today.",
    options: [
      "Whoever finishes first can leave early today.",
      "Whatever finishes first can leave early today.",
      "Whoever finished first can leave early today.",
    ],
    correctOptionIndex: 0,
    xpReward: 14,
  },
  {
    id: 'li-18',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: 'The new policy will take effect starting next Monday.',
    options: [
      'The new policy will take effect starting next Monday.',
      'The new policy took effect starting last Monday.',
      'The new policy will take affect starting next Monday.',
    ],
    correctOptionIndex: 0,
    xpReward: 12,
  },
  {
    id: 'li-19',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: "I'd rather stay in tonight than go out.",
    options: [
      "I'd rather stay in tonight than go out.",
      "I'd rather stayed in tonight than go out.",
      "I'd rather stay out tonight than go in.",
    ],
    correctOptionIndex: 0,
    xpReward: 12,
  },
  {
    id: 'li-20',
    type: ExerciseType.Listening,
    prompt: 'Listen and choose what you heard.',
    audioText: "Not only did she finish on time, but she also exceeded expectations.",
    options: [
      "Not only she finished on time, but she also exceeded expectations.",
      "Not only did she finish on time, but she also exceeded expectations.",
      "Not only did she finish on time, and she also exceeded expectations.",
    ],
    correctOptionIndex: 1,
    xpReward: 16,
  },
];
