import { CefrLevel } from '../../models';
import { ExerciseType } from '../../models';
import { Lesson } from '../../models';
import { Skill } from '../../models';

export const MOCK_LESSONS: Lesson[] = [
  {
    id: 'en-a1-verb-to-be',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Verb "to be"',
    description: 'Learn to say who you are and how you feel.',
    iconEmoji: '🌱',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 8,
    xpReward: 30,
    order: 1,
    requiresLessonIds: [],
    explanation:
      'The verb "to be" (am / is / are) is used to talk about identity, feelings and states. "I am happy", "She is a doctor", "They are from Spain".',
    examples: ['I am a student.', 'You are late.', 'He is tired.', 'We are ready.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct form: "She ___ a teacher."',
        options: ['am', 'is', 'are', 'be'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'They ___ from Canada.',
        options: ['am', 'is', 'are', 'was'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"I is happy" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-a1-pronouns',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Personal Pronouns',
    description: 'Learn to say I, you, he, she, it, we, they.',
    iconEmoji: '👤',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 8,
    xpReward: 30,
    order: 2,
    requiresLessonIds: ['en-a1-verb-to-be'],
    explanation:
      'Personal pronouns replace nouns: I, you, he, she, it, we, they. Use "he" for males, "she" for females, "it" for things and animals, and "they" for plural.',
    examples: ['I am from Mexico.', 'She is my sister.', 'It is a new phone.', 'They are my friends.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Which pronoun replaces "Maria and John"?',
        options: ['He', 'She', 'It', 'They'],
        correctOptionIndex: 3,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: '___ is my brother. He lives in Bogota.',
        options: ['She', 'He', 'It', 'They'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"It" can be used to refer to a dog.',
        correctAnswer: true,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-a1-articles',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Articles: a, an, the',
    description: 'Learn when to use a, an and the.',
    iconEmoji: '📎',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 9,
    xpReward: 30,
    order: 3,
    requiresLessonIds: ['en-a1-pronouns'],
    explanation:
      'Use "a" before a consonant sound ("a car"), "an" before a vowel sound ("an apple"), and "the" when talking about something specific that both speakers know ("the car I bought").',
    examples: ['I have a dog.', 'She ate an orange.', 'The book on the table is mine.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct article: "She is ___ engineer."',
        options: ['a', 'an', 'the', '(no article)'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'Can you close ___ door, please?',
        options: ['a', 'an', 'the', '(no article)'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"an university" is correct because "university" starts with a vowel letter.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-a2-past-simple',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Past Simple',
    description: 'Talk about finished actions in the past.',
    iconEmoji: '⏳',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 12,
    xpReward: 40,
    order: 4,
    requiresLessonIds: ['en-a1-articles'],
    explanation:
      'Use the Past Simple for actions that started and finished in the past. Regular verbs add "-ed" ("worked"); irregular verbs change form ("went", "ate").',
    examples: ['I worked yesterday.', 'She went to the park.', 'They didn\'t call me.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'I ___ to the supermarket yesterday.',
        options: ['go', 'goes', 'went', 'going'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.WordOrder,
        prompt: 'Put the words in the correct order.',
        shuffledWords: ['English', 'every', 'I', 'study', 'day'],
        correctSentence: 'I study English every day',
        xpReward: 15,
      },
      {
        id: 'ex-3',
        type: ExerciseType.Translation,
        prompt: 'Translate to English.',
        sourceText: 'Yo trabajé todos los días.',
        acceptedAnswers: ['I worked every day', 'I worked every day.'],
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-a2-future',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Future: will vs going to',
    description: 'Talk about future plans and predictions.',
    iconEmoji: '🔮',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 12,
    xpReward: 40,
    order: 5,
    requiresLessonIds: ['en-a2-past-simple'],
    explanation:
      'Use "going to" for plans already decided ("I am going to visit my parents") and "will" for spontaneous decisions or predictions ("I think it will rain").',
    examples: ["I'm going to start a new job next month.", 'It will probably rain later.', "I'll help you with that."],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the best option: "Look at those clouds! It ___ rain."',
        options: ['is going to', 'will', 'is', 'was going to'],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: "The phone is ringing, I ___ answer it.",
        options: ["'ll", 'am going to', 'was', 'do'],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.Translation,
        prompt: 'Translate to English.',
        sourceText: 'Voy a viajar a Europa el próximo año.',
        acceptedAnswers: [
          "I'm going to travel to Europe next year",
          "I'm going to travel to Europe next year.",
          'I am going to travel to Europe next year',
          'I am going to travel to Europe next year.',
        ],
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-a2-comparatives',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Comparatives and Superlatives',
    description: 'Compare people, places and things.',
    iconEmoji: '📏',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 12,
    xpReward: 40,
    order: 6,
    requiresLessonIds: ['en-a2-future'],
    explanation:
      'Short adjectives add "-er/-est" ("faster", "fastest"). Long adjectives use "more/most" ("more expensive", "most expensive"). Irregular forms exist too ("good, better, best").',
    examples: ['This car is faster than that one.', 'She is the most experienced worker here.', 'Today is better than yesterday.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct comparative: "This laptop is ___ than mine."',
        options: ['expensive', 'more expensive', 'expensiver', 'most expensive'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'She is the ___ student in the class.',
        options: ['good', 'better', 'best', 'more good'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.WordOrder,
        prompt: 'Put the words in the correct order.',
        shuffledWords: ['is', 'than', 'taller', 'brother', 'my', 'me'],
        correctSentence: 'my brother is taller than me',
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-b1-present-perfect',
    language: 'en',
    level: CefrLevel.B1,
    title: 'Present Perfect',
    description: 'Connect the past with the present.',
    iconEmoji: '🔗',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 15,
    xpReward: 45,
    order: 7,
    requiresLessonIds: ['en-a2-comparatives'],
    explanation:
      'Use "have/has + past participle" for experiences or actions with a result in the present. "I have visited Paris" (at some point in my life). "She has just arrived" (very recently).',
    examples: ['I have seen that movie.', 'He has finished his homework.', 'We haven\'t eaten yet.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence.',
        options: [
          'I have seen that movie.',
          'I have saw that movie.',
          'I has seen that movie.',
          'I having seen that movie.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.Listening,
        prompt: 'Listen and choose what you heard.',
        audioText: 'She has already finished her project.',
        options: [
          'She has already finished her project.',
          'She already finishes her project.',
          'She had finished her project.',
        ],
        correctOptionIndex: 0,
        xpReward: 15,
      },
      {
        id: 'ex-3',
        type: ExerciseType.Reading,
        prompt: 'Read the text and answer.',
        passage:
          'Maria has lived in three different countries. She has learned two new languages and has made friends everywhere she has gone.',
        questions: [
          {
            id: 'ex-3-q1',
            type: ExerciseType.MultipleChoice,
            prompt: 'How many languages has Maria learned?',
            options: ['One', 'Two', 'Three', 'None'],
            correctOptionIndex: 1,
            xpReward: 10,
          },
        ],
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-b1-conditionals',
    language: 'en',
    level: CefrLevel.B1,
    title: 'First and Second Conditional',
    description: 'Talk about real and hypothetical situations.',
    iconEmoji: '🔀',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 15,
    xpReward: 45,
    order: 8,
    requiresLessonIds: ['en-b1-present-perfect'],
    explanation:
      'First conditional (real/possible future): "If + present simple, will + verb" — "If it rains, I will stay home." Second conditional (hypothetical/unreal): "If + past simple, would + verb" — "If I won the lottery, I would travel the world."',
    examples: [
      'If I have time, I will call you.',
      'If I were you, I would apply for that job.',
      "If she studied more, she would pass the exam.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence.',
        options: [
          'If I win the lottery, I will travel the world.',
          'If I would win the lottery, I will travel the world.',
          'If I win the lottery, I would travel the world.',
          'If I winning the lottery, I will travel the world.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence (hypothetical).',
        sentenceWithBlank: 'If I ___ more money, I would buy a new car.',
        options: ['have', 'had', 'will have', 'has'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.Translation,
        prompt: 'Translate to English.',
        sourceText: 'Si llueve mañana, me quedaré en casa.',
        acceptedAnswers: [
          'If it rains tomorrow, I will stay home',
          'If it rains tomorrow, I will stay home.',
          "If it rains tomorrow, I'll stay home",
          "If it rains tomorrow, I'll stay home.",
        ],
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-b1-passive-voice',
    language: 'en',
    level: CefrLevel.B1,
    title: 'Passive Voice',
    description: 'Focus on the action instead of who does it.',
    iconEmoji: '🎯',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 15,
    xpReward: 45,
    order: 9,
    requiresLessonIds: ['en-b1-conditionals'],
    explanation:
      'The passive voice ("be + past participle") is used when the action matters more than who does it. "The report was submitted yesterday" instead of "Someone submitted the report yesterday."',
    examples: [
      'The email was sent this morning.',
      'The new policy will be announced next week.',
      'The building was designed by a famous architect.',
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the passive form of: "They deliver the packages on Fridays."',
        options: [
          'The packages are delivered on Fridays.',
          'The packages deliver on Fridays.',
          'The packages were delivering on Fridays.',
          'The packages delivered on Fridays.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence in the passive.',
        sentenceWithBlank: 'The report ___ by the end of the day.',
        options: ['will submit', 'will be submitted', 'submitted', 'is submitting'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"The cake was baked by my mother" is an example of the passive voice.',
        correctAnswer: true,
        xpReward: 10,
      },
    ],
  },

  // ============================================================= B2 ===
  {
    id: 'en-b2-mixed-conditionals',
    language: 'en',
    level: CefrLevel.B2,
    title: 'Mixed Conditionals',
    description: 'Talk about how a past decision affects the present, or how a present situation would have changed the past.',
    iconEmoji: '🔀',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 18,
    xpReward: 55,
    order: 10,
    requiresLessonIds: ['en-b1-passive-voice'],
    explanation:
      'Mixed conditionals combine a condition from one time with a result in another. Past condition → present result: "If I had taken that job, I would be living in Madrid now." Present condition → past result: "If she weren\'t so organized, she wouldn\'t have finished the project on time."',
    examples: [
      "If he hadn't missed the flight, he would be at the conference right now.",
      "If I spoke French, I would have understood the client's email.",
      "If we hadn't upgraded the system last year, we would be struggling with today's volume.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct mixed conditional: "If she ___ harder for the exam, she would be at university now."',
        options: ['studies', 'had studied', 'would study', 'studied'],
        correctOptionIndex: 1,
        xpReward: 12,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: "If he weren't so careless, he ___ his badge at home this morning.",
        options: ["wouldn't have left", "won't leave", "doesn't leave", "hasn't left"],
        correctOptionIndex: 0,
        xpReward: 12,
      },
      {
        id: 'ex-3',
        type: ExerciseType.WordOrder,
        prompt: 'Put the words in order to form a correct mixed conditional.',
        shuffledWords: ['I', 'would', 'the', 'if', 'promotion', 'have', 'harder', 'worked', 'gotten', 'I'],
        correctSentence: 'if I worked harder I would have gotten the promotion',
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-b2-passive-advanced',
    language: 'en',
    level: CefrLevel.B2,
    title: 'Advanced Passive Voice',
    description: 'Use the passive with modals and perfect tenses for formal, professional writing.',
    iconEmoji: '🧩',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 16,
    xpReward: 50,
    order: 11,
    requiresLessonIds: ['en-b2-mixed-conditionals'],
    explanation:
      'Beyond the simple passive, English combines "be" with modals ("must be reviewed", "can be fixed") and with perfect tenses ("has been approved", "had been delayed") to sound formal and precise — very common in reports, policies and professional emails.',
    examples: [
      'This request must be approved by a supervisor before Friday.',
      'The order has already been shipped.',
      'The delay had been caused by a system update.',
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence.',
        options: [
          'The invoice can sent by email.',
          'The invoice can be sent by email.',
          'The invoice can be send by email.',
          'The invoice can being sent by email.',
        ],
        correctOptionIndex: 1,
        xpReward: 12,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence with the modal passive.',
        sentenceWithBlank: 'All complaints ___ within 48 hours.',
        options: ['must respond', 'must be responded to', 'must responded', 'must be respond'],
        correctOptionIndex: 1,
        xpReward: 12,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"The issue has been resolved" uses the present perfect passive.',
        correctAnswer: true,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-b2-modals-deduction',
    language: 'en',
    level: CefrLevel.B2,
    title: 'Modals of Deduction',
    description: 'Guess what probably happened using must have, might have, and can\'t have.',
    iconEmoji: '🔍',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 15,
    xpReward: 50,
    order: 12,
    requiresLessonIds: ['en-b2-passive-advanced'],
    explanation:
      'Use "must have + past participle" when you\'re almost certain something happened, "might/could have" when it\'s possible, and "can\'t have" when you\'re sure it didn\'t. "She isn\'t answering — she must have left already." "He might have forgotten the meeting." "They can\'t have finished — it\'s only been five minutes."',
    examples: [
      "The customer sounds furious — something must have gone wrong with the order.",
      'He might have missed the email; let\'s check with him directly.',
      "She can't have submitted the report — the deadline isn't until tomorrow.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: "The line went dead. She ___ hung up by accident.",
        options: ['must', 'must have', 'must to', 'must has'],
        correctOptionIndex: 1,
        xpReward: 12,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete with the correct modal of deduction.',
        sentenceWithBlank: 'The package is still at the warehouse — it ___ been sent yet.',
        options: ["can't have", 'must have', 'should have', 'would have'],
        correctOptionIndex: 0,
        xpReward: 12,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"Might have" expresses total certainty about the past.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-b2-future-forms',
    language: 'en',
    level: CefrLevel.B2,
    title: 'Future Perfect and Future Continuous',
    description: 'Talk about what will already be finished, or what will be in progress, at a point in the future.',
    iconEmoji: '⏳',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 16,
    xpReward: 52,
    order: 13,
    requiresLessonIds: ['en-b2-modals-deduction'],
    explanation:
      'Future perfect ("will have + past participle") describes something that will be completed before a point in the future. Future continuous ("will be + -ing") describes something in progress at a specific future moment. "By 6pm, I will have finished the report." "This time next week, I\'ll be presenting to the client."',
    examples: [
      'By the end of the quarter, we will have onboarded twenty new clients.',
      'At 9am tomorrow, she will be flying to the conference.',
      "In two years, he will have worked here for a decade.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence.',
        options: [
          'By Friday, I will finish the training.',
          'By Friday, I will have finished the training.',
          'By Friday, I will be finish the training.',
          'By Friday, I have finished the training.',
        ],
        correctOptionIndex: 1,
        xpReward: 12,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete with the future continuous.',
        sentenceWithBlank: 'This time tomorrow, we ___ the new system live.',
        options: ['will demonstrate', 'will be demonstrating', 'will have demonstrated', 'demonstrate'],
        correctOptionIndex: 1,
        xpReward: 12,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: 'Future perfect is used to say something will be completed before a specific future time.',
        correctAnswer: true,
        xpReward: 10,
      },
    ],
  },

  // ============================================================= C1 ===
  {
    id: 'en-c1-inversion',
    language: 'en',
    level: CefrLevel.C1,
    title: 'Inversion for Emphasis',
    description: 'Front a negative or limiting adverb and invert the subject and verb for a more formal, emphatic tone.',
    iconEmoji: '🔁',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 18,
    xpReward: 60,
    order: 14,
    requiresLessonIds: ['en-b2-future-forms'],
    explanation:
      'Starting a sentence with a negative/limiting adverb ("Never", "Rarely", "Not only", "Under no circumstances") triggers subject-auxiliary inversion, the same word order as a question. "Never have I seen such a disorganized handover." This is formal and emphatic — common in presentations, reports and formal writing, not everyday conversation.',
    examples: [
      "Rarely does a client escalate this quickly without warning.",
      "Not only did the update fix the bug, but it also improved load times.",
      "Under no circumstances should this data be shared externally.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correctly inverted sentence.',
        options: [
          'Never I have seen such a fast resolution.',
          'Never have I seen such a fast resolution.',
          'Never have seen I such a fast resolution.',
          'I never have seen such a fast resolution.',
        ],
        correctOptionIndex: 1,
        xpReward: 15,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the inverted sentence.',
        sentenceWithBlank: 'Not only ___ late, but he also forgot the documents.',
        options: ['he was', 'was he', 'he is', 'is he'],
        correctOptionIndex: 1,
        xpReward: 15,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: 'Inversion after a negative adverb is typically used in casual spoken English.',
        correctAnswer: false,
        xpReward: 12,
      },
    ],
  },
  {
    id: 'en-c1-cleft-sentences',
    language: 'en',
    level: CefrLevel.C1,
    title: 'Cleft Sentences',
    description: 'Use "It was..." and "What... is..." structures to emphasize exactly the part of a sentence that matters.',
    iconEmoji: '🎯',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 17,
    xpReward: 58,
    order: 15,
    requiresLessonIds: ['en-c1-inversion'],
    explanation:
      'Cleft sentences split one idea into two clauses to put emphasis exactly where you want it. It-cleft: "It was the delivery delay that upset the client" (not the price). What-cleft: "What frustrated the team was the lack of communication." Both are more precise and emphatic than a plain statement.',
    examples: [
      "It was the manager who approved the refund, not the agent.",
      "What we need is a clearer escalation process.",
      "It was only after the third call that the issue got resolved.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct cleft sentence emphasizing "the training" as the cause.',
        options: [
          'It was the training that made the difference.',
          'It was that the training made the difference.',
          'The training it was that made the difference.',
          'It the training was that made the difference.',
        ],
        correctOptionIndex: 0,
        xpReward: 14,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the what-cleft sentence.',
        sentenceWithBlank: '___ really matters here is customer trust.',
        options: ['It', 'What', 'That', 'Which'],
        correctOptionIndex: 1,
        xpReward: 14,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: 'Cleft sentences are used to emphasize a specific part of a message.',
        correctAnswer: true,
        xpReward: 12,
      },
    ],
  },
  {
    id: 'en-c1-participle-clauses',
    language: 'en',
    level: CefrLevel.C1,
    title: 'Participle Clauses',
    description: 'Combine two ideas into one smoother sentence using -ing and -ed clauses.',
    iconEmoji: '🧵',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 17,
    xpReward: 58,
    order: 16,
    requiresLessonIds: ['en-c1-cleft-sentences'],
    explanation:
      'A participle clause replaces a longer clause with the same subject, making writing more fluid. "Having reviewed the account, she approved the refund" (= After she reviewed...). "Concerned about the delay, the client called twice." Watch for dangling participles — the participle clause must share its subject with the main clause.',
    examples: [
      "Having checked the system logs, the technician identified the cause.",
      "Frustrated by the wait, the customer asked to speak to a manager.",
      "Not having received a reply, we followed up by phone.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the sentence with a correctly used participle clause.',
        options: [
          'Having finished the call, the notes were saved.',
          'Having finished the call, she saved the notes.',
          'Having finish the call, she saved the notes.',
          'Have finished the call, she saved the notes.',
        ],
        correctOptionIndex: 1,
        xpReward: 14,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the participle clause.',
        sentenceWithBlank: '___ by the noise, the agent asked the customer to move to a quieter room.',
        options: ['Distract', 'Distracted', 'Distracting', 'To distract'],
        correctOptionIndex: 1,
        xpReward: 14,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"Having finished the call, the notes were saved" is a correctly attached participle clause.',
        correctAnswer: false,
        xpReward: 12,
      },
    ],
  },
  {
    id: 'en-c1-reported-advanced',
    language: 'en',
    level: CefrLevel.C1,
    title: 'Advanced Reporting Structures',
    description: 'Report suggestions, demands and insistence naturally, using patterns beyond basic reported speech.',
    iconEmoji: '🗣️',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 16,
    xpReward: 56,
    order: 17,
    requiresLessonIds: ['en-c1-participle-clauses'],
    explanation:
      'Verbs like "suggest," "insist," "demand," and "recommend" are often followed by "that + subject + base form" (the subjunctive), not a normal tense: "The manager insisted that the report be resubmitted." "She suggested that he contact billing directly."',
    examples: [
      "The client demanded that the charge be reversed immediately.",
      "The team recommended that the deadline be extended.",
      "He suggested that she check her spam folder.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct reporting structure.',
        options: [
          'She insisted that he calls back.',
          'She insisted that he called back.',
          'She insisted that he call back.',
          'She insisted him to call back.',
        ],
        correctOptionIndex: 2,
        xpReward: 14,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'The supervisor recommended that the ticket ___ escalated.',
        options: ['is', 'was', 'be', 'being'],
        correctOptionIndex: 2,
        xpReward: 14,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: 'After "insist that", English uses the base form of the verb, not "-s" for third person.',
        correctAnswer: true,
        xpReward: 12,
      },
    ],
  },

  // ============================================================= C2 ===
  {
    id: 'en-c2-ellipsis',
    language: 'en',
    level: CefrLevel.C2,
    title: 'Ellipsis and Substitution',
    description: 'Avoid repeating words naturally, the way fluent speakers do.',
    iconEmoji: '✂️',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 18,
    xpReward: 65,
    order: 18,
    requiresLessonIds: ['en-c1-reported-advanced'],
    explanation:
      'Native-like English drops repeated words (ellipsis) or replaces them with "so"/"do"/"one" (substitution) instead of repeating the full phrase. "She can handle escalations, and he can too" (not "he can handle escalations too"). "I think it will work." "I think so too."',
    examples: [
      "He wanted to renew the contract, and so did his manager.",
      "I haven't reviewed the proposal yet, but I intend to.",
      "There were two options; we chose the cheaper one.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the most natural sentence.',
        options: [
          'She can speak Portuguese, and he can speak Portuguese too.',
          'She can speak Portuguese, and he can too.',
          'She can speak Portuguese, and he can also.',
          'She can speak Portuguese, he can speak too Portuguese.',
        ],
        correctOptionIndex: 1,
        xpReward: 16,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete with the natural substitution.',
        sentenceWithBlank: "I don't think it will rain, but she thinks ___.",
        options: ['so', 'that', 'it', 'yes'],
        correctOptionIndex: 0,
        xpReward: 16,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: 'Ellipsis means adding extra words for clarity.',
        correctAnswer: false,
        xpReward: 13,
      },
    ],
  },
  {
    id: 'en-c2-emphasis',
    language: 'en',
    level: CefrLevel.C2,
    title: 'Emphasis and Fronting',
    description: 'Move part of a sentence to the front for rhetorical effect — precise, native-level emphasis.',
    iconEmoji: '📣',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 18,
    xpReward: 65,
    order: 19,
    requiresLessonIds: ['en-c2-ellipsis'],
    explanation:
      'Fronting moves an element that would normally come later to the start of the sentence, for emphasis. "Such was the pressure that she had to take a break." "Little did they know the account was already flagged." This is a sophisticated, deliberate stylistic choice, common in formal writing and speeches.',
    examples: [
      "So confident was the candidate that the interviewers were impressed immediately.",
      "Little did we realize how much the policy change would affect retention.",
      "Such was the client's frustration that a full refund was the only option.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correctly fronted sentence.',
        options: [
          'Little we knew the deal would fall through.',
          'Little did we know the deal would fall through.',
          'Little we did know the deal would fall through.',
          'We little did know the deal would fall through.',
        ],
        correctOptionIndex: 1,
        xpReward: 17,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the fronted sentence.',
        sentenceWithBlank: 'Such ___ the demand that we ran out of stock within an hour.',
        options: ['was', 'is', 'were', 'had'],
        correctOptionIndex: 0,
        xpReward: 17,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: 'Fronting for emphasis is a purely informal, casual-speech pattern.',
        correctAnswer: false,
        xpReward: 13,
      },
    ],
  },
  {
    id: 'en-c2-register',
    language: 'en',
    level: CefrLevel.C2,
    title: 'Register Shifts',
    description: 'Recognize and produce the grammatical differences between formal and informal English, not just vocabulary.',
    iconEmoji: '🎭',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 19,
    xpReward: 68,
    order: 20,
    requiresLessonIds: ['en-c2-emphasis'],
    explanation:
      "Register isn't only about word choice — grammar shifts too. Formal English avoids contractions and phrasal verbs, prefers passive/nominalized structures, and full modal forms: \"We regret to inform you that your request cannot be processed\" vs. \"Sorry, we can't do that.\" Choosing the right register is as much a grammar skill as a vocabulary one.",
    examples: [
      "Formal: We would be grateful if you could confirm receipt.\nInformal: Can you let us know you got this?",
      "Formal: The matter is currently under review.\nInformal: We're still looking into it.",
      "Formal: Should you require further assistance, please do not hesitate to contact us.\nInformal: Let us know if you need anything else.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Which sentence is appropriate for a formal business email?',
        options: [
          "We can't sort that out right now.",
          'We are unable to resolve this at present.',
          "Can't help with that today.",
          "That's not gonna happen today.",
        ],
        correctOptionIndex: 1,
        xpReward: 17,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Choose the formal equivalent.',
        sentenceWithBlank: 'Informal: "We\'ll get back to you soon." Formal: "We ___ respond at our earliest convenience."',
        options: ['will', 'gonna', 'are gonna', "'ll"],
        correctOptionIndex: 0,
        xpReward: 17,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: 'Register is only about vocabulary, never grammar.',
        correctAnswer: false,
        xpReward: 14,
      },
    ],
  },
  {
    id: 'en-c2-discourse-markers',
    language: 'en',
    level: CefrLevel.C2,
    title: 'Advanced Discourse Markers',
    description: 'Use precise connectors like "that said," "in light of," and "notwithstanding" to signal exactly the right relationship between ideas.',
    iconEmoji: '🔗',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 19,
    xpReward: 68,
    order: 21,
    requiresLessonIds: ['en-c2-register'],
    explanation:
      'Advanced discourse markers signal precise logical relationships: "that said" (contrast, but softer than "however"), "in light of" (given new information), "notwithstanding" (despite, very formal), "that being said" (acknowledging a point before adding a caveat). Choosing the wrong one can subtly misrepresent your point.',
    examples: [
      "The results were disappointing. That said, we learned a lot for next quarter.",
      "In light of the recent outage, we're reviewing our infrastructure.",
      "The project succeeded, notwithstanding several early setbacks.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the most precise connector: "The client was upset. ___, they agreed to continue the contract."',
        options: ['Therefore', 'That said', 'Similarly', 'For example'],
        correctOptionIndex: 1,
        xpReward: 17,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete with the most precise connector.',
        sentenceWithBlank: '___ the new data, we\'re revising our forecast.',
        options: ['In light of', 'Despite', 'Although', 'Because'],
        correctOptionIndex: 0,
        xpReward: 17,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"Notwithstanding" means "despite" and is used in formal English.',
        correctAnswer: true,
        xpReward: 14,
      },
    ],
  },
];
