import { ExerciseType, MultipleChoiceExercise } from '../../models';

/** Customer service situations — reuses the exercise player's multiple-choice type. */
export const MOCK_INTERVIEW_SCENARIOS: MultipleChoiceExercise[] = [
  {
    id: 'sc-1',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer calls because they were charged twice for the same order. What would you do?',
    options: [
      "Tell the customer it's not your problem.",
      'Apologize, verify the account and investigate the charge.',
      'Transfer the customer immediately.',
      'End the call.',
    ],
    correctOptionIndex: 1,
    explanation: 'Always apologize for the inconvenience, verify the details, and investigate before offering a solution.',
    xpReward: 10,
  },
  {
    id: 'sc-2',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer asks for a refund outside of the return policy. What is the best response?',
    options: [
      'Refuse immediately and hang up.',
      'Explain the policy clearly and offer any alternative options available.',
      'Promise a refund you cannot guarantee.',
      'Ignore the request.',
    ],
    correctOptionIndex: 1,
    explanation: 'Be honest about the policy, but always look for an alternative — that keeps the interaction professional and helpful.',
    xpReward: 10,
  },
  {
    id: 'sc-3',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer says the product they received is damaged. What should you do first?',
    options: [
      'Apologize and ask for details (order number, description of the damage).',
      'Tell them to contact the manufacturer.',
      'Assume they are lying.',
      'Immediately offer a full refund without checking anything.',
    ],
    correctOptionIndex: 0,
    explanation: 'Gather information first — you need the order details before you can offer the right solution.',
    xpReward: 10,
  },
  {
    id: 'sc-4',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer is confused about how to use a feature. What is the best approach?',
    options: [
      'Explain quickly using technical terms.',
      'Tell them to read the manual.',
      'Explain step by step in simple language, and confirm they understood.',
      'Transfer them without explanation.',
    ],
    correctOptionIndex: 2,
    explanation: 'Simple, step-by-step explanations with confirmation work best for confused customers.',
    xpReward: 10,
  },
  {
    id: 'sc-5',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer wants to cancel their subscription. What should you do?',
    options: [
      'Refuse to process the cancellation.',
      'Confirm the details, process it professionally, and ask if there is anything you can improve.',
      'Try to guilt them into staying.',
      'Hang up.',
    ],
    correctOptionIndex: 1,
    explanation: 'Respect the customer\'s decision. A professional, no-pressure cancellation leaves a good final impression.',
    xpReward: 10,
  },
  {
    id: 'sc-6',
    type: ExerciseType.MultipleChoice,
    prompt: "A customer's issue is outside your ability to resolve. What is the correct action?",
    options: [
      'Tell them you cannot help and end the call.',
      'Guess an answer so you seem helpful.',
      'Escalate to a supervisor or the right department, and explain what happens next.',
      'Put them on hold indefinitely.',
    ],
    correctOptionIndex: 2,
    explanation: 'Escalating with a clear explanation of next steps keeps the customer informed and confident.',
    xpReward: 10,
  },
  {
    id: 'sc-7',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer asks a question you genuinely don\'t know the answer to. What should you say?',
    options: [
      'Make up an answer that sounds plausible.',
      '"I\'m not sure, but let me find out for you."',
      'Stay silent.',
      'Tell them to search online.',
    ],
    correctOptionIndex: 1,
    explanation: 'Honesty builds trust. Never guess — find the real answer and follow up.',
    xpReward: 10,
  },
  {
    id: 'sc-8',
    type: ExerciseType.MultipleChoice,
    prompt: 'A long-time customer complains about a recent price increase. Best response?',
    options: [
      'Explain the reason for the change and thank them for their loyalty.',
      'Tell them prices always go up, nothing you can do.',
      'Offer a discount you\'re not authorized to give.',
      'Argue with them.',
    ],
    correctOptionIndex: 0,
    explanation: 'Acknowledge their loyalty and explain calmly — customers respond well to being valued.',
    xpReward: 10,
  },
  {
    id: 'sc-9',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer is on a bad connection and you can barely hear them. What do you do?',
    options: [
      'Pretend you understood.',
      'Politely ask them to repeat, or offer to call them back.',
      'Hang up.',
      'Guess what they said.',
    ],
    correctOptionIndex: 1,
    explanation: 'It\'s always better to ask for clarification than to guess and make a mistake.',
    xpReward: 10,
  },
  {
    id: 'sc-10',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer wants a discount that is not part of any current promotion. What should you say?',
    options: [
      'Give them the discount anyway.',
      'Explain that this specific discount isn\'t available, and mention any current offers instead.',
      'Say "no" and move on quickly.',
      'Ignore the request.',
    ],
    correctOptionIndex: 1,
    explanation: 'Being clear but offering an alternative keeps the conversation positive and honest.',
    xpReward: 10,
  },
  {
    id: 'sc-11',
    type: ExerciseType.MultipleChoice,
    prompt: 'Near the end of your shift, a customer calls with a complex issue that will take time. What do you do?',
    options: [
      'Rush through it to end your shift on time.',
      'Tell them to call back tomorrow.',
      'Give the same quality of attention as any other call, even if it takes longer.',
      'Transfer immediately without trying to help.',
    ],
    correctOptionIndex: 2,
    explanation: 'Professionalism means consistent quality of service, regardless of the time.',
    xpReward: 10,
  },
  {
    id: 'sc-12',
    type: ExerciseType.MultipleChoice,
    prompt: 'A customer says a competitor offers a better price. How should you respond?',
    options: [
      'Criticize the competitor.',
      'Focus on the value and benefits your company provides.',
      'Immediately match any price they mention.',
      "Tell them to go with the competitor then.",
    ],
    correctOptionIndex: 1,
    explanation: 'Highlighting your own value is more professional and effective than criticizing competitors.',
    xpReward: 10,
  },
];
