import { CefrLevel } from '../../models';
import { ExerciseType } from '../../models';
import { Lesson } from '../../models';
import { Skill } from '../../models';

export const MOCK_LESSONS: Lesson[] = [
  {
    id: 'en-a1-verb-to-be',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Verb "to be"',
    description: 'Learn to say who you are and how you feel.',
    iconEmoji: '🌱',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 8,
    xpReward: 30,
    order: 1,
    requiresLessonIds: [],
    explanation:
      'The verb "to be" (am / is / are) is used to talk about identity, feelings and states. "I am happy", "She is a doctor", "They are from Spain".',
    examples: ['I am a student.', 'You are late.', 'He is tired.', 'We are ready.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct form: "She ___ a teacher."',
        options: ['am', 'is', 'are', 'be'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'They ___ from Canada.',
        options: ['am', 'is', 'are', 'was'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"I is happy" is correct English.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-a1-pronouns',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Personal Pronouns',
    description: 'Learn to say I, you, he, she, it, we, they.',
    iconEmoji: '👤',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 8,
    xpReward: 30,
    order: 2,
    requiresLessonIds: ['en-a1-verb-to-be'],
    explanation:
      'Personal pronouns replace nouns: I, you, he, she, it, we, they. Use "he" for males, "she" for females, "it" for things and animals, and "they" for plural.',
    examples: ['I am from Mexico.', 'She is my sister.', 'It is a new phone.', 'They are my friends.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Which pronoun replaces "Maria and John"?',
        options: ['He', 'She', 'It', 'They'],
        correctOptionIndex: 3,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: '___ is my brother. He lives in Bogota.',
        options: ['She', 'He', 'It', 'They'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"It" can be used to refer to a dog.',
        correctAnswer: true,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-a1-articles',
    language: 'en',
    level: CefrLevel.A1,
    title: 'Articles: a, an, the',
    description: 'Learn when to use a, an and the.',
    iconEmoji: '📎',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 9,
    xpReward: 30,
    order: 3,
    requiresLessonIds: ['en-a1-pronouns'],
    explanation:
      'Use "a" before a consonant sound ("a car"), "an" before a vowel sound ("an apple"), and "the" when talking about something specific that both speakers know ("the car I bought").',
    examples: ['I have a dog.', 'She ate an orange.', 'The book on the table is mine.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct article: "She is ___ engineer."',
        options: ['a', 'an', 'the', '(no article)'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'Can you close ___ door, please?',
        options: ['a', 'an', 'the', '(no article)'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"an university" is correct because "university" starts with a vowel letter.',
        correctAnswer: false,
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-a2-past-simple',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Past Simple',
    description: 'Talk about finished actions in the past.',
    iconEmoji: '⏳',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 12,
    xpReward: 40,
    order: 4,
    requiresLessonIds: ['en-a1-articles'],
    explanation:
      'Use the Past Simple for actions that started and finished in the past. Regular verbs add "-ed" ("worked"); irregular verbs change form ("went", "ate").',
    examples: ['I worked yesterday.', 'She went to the park.', 'They didn\'t call me.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'I ___ to the supermarket yesterday.',
        options: ['go', 'goes', 'went', 'going'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.WordOrder,
        prompt: 'Put the words in the correct order.',
        shuffledWords: ['English', 'every', 'I', 'study', 'day'],
        correctSentence: 'I study English every day',
        xpReward: 15,
      },
      {
        id: 'ex-3',
        type: ExerciseType.Translation,
        prompt: 'Translate to English.',
        sourceText: 'Yo trabajé todos los días.',
        acceptedAnswers: ['I worked every day', 'I worked every day.'],
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-a2-future',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Future: will vs going to',
    description: 'Talk about future plans and predictions.',
    iconEmoji: '🔮',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 12,
    xpReward: 40,
    order: 5,
    requiresLessonIds: ['en-a2-past-simple'],
    explanation:
      'Use "going to" for plans already decided ("I am going to visit my parents") and "will" for spontaneous decisions or predictions ("I think it will rain").',
    examples: ["I'm going to start a new job next month.", 'It will probably rain later.', "I'll help you with that."],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the best option: "Look at those clouds! It ___ rain."',
        options: ['is going to', 'will', 'is', 'was going to'],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: "The phone is ringing, I ___ answer it.",
        options: ["'ll", 'am going to', 'was', 'do'],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.Translation,
        prompt: 'Translate to English.',
        sourceText: 'Voy a viajar a Europa el próximo año.',
        acceptedAnswers: [
          "I'm going to travel to Europe next year",
          "I'm going to travel to Europe next year.",
          'I am going to travel to Europe next year',
          'I am going to travel to Europe next year.',
        ],
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-a2-comparatives',
    language: 'en',
    level: CefrLevel.A2,
    title: 'Comparatives and Superlatives',
    description: 'Compare people, places and things.',
    iconEmoji: '📏',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 12,
    xpReward: 40,
    order: 6,
    requiresLessonIds: ['en-a2-future'],
    explanation:
      'Short adjectives add "-er/-est" ("faster", "fastest"). Long adjectives use "more/most" ("more expensive", "most expensive"). Irregular forms exist too ("good, better, best").',
    examples: ['This car is faster than that one.', 'She is the most experienced worker here.', 'Today is better than yesterday.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct comparative: "This laptop is ___ than mine."',
        options: ['expensive', 'more expensive', 'expensiver', 'most expensive'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence.',
        sentenceWithBlank: 'She is the ___ student in the class.',
        options: ['good', 'better', 'best', 'more good'],
        correctOptionIndex: 2,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.WordOrder,
        prompt: 'Put the words in the correct order.',
        shuffledWords: ['is', 'than', 'taller', 'brother', 'my', 'me'],
        correctSentence: 'my brother is taller than me',
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-b1-present-perfect',
    language: 'en',
    level: CefrLevel.B1,
    title: 'Present Perfect',
    description: 'Connect the past with the present.',
    iconEmoji: '🔗',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 15,
    xpReward: 45,
    order: 7,
    requiresLessonIds: ['en-a2-comparatives'],
    explanation:
      'Use "have/has + past participle" for experiences or actions with a result in the present. "I have visited Paris" (at some point in my life). "She has just arrived" (very recently).',
    examples: ['I have seen that movie.', 'He has finished his homework.', 'We haven\'t eaten yet.'],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence.',
        options: [
          'I have seen that movie.',
          'I have saw that movie.',
          'I has seen that movie.',
          'I having seen that movie.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.Listening,
        prompt: 'Listen and choose what you heard.',
        audioText: 'She has already finished her project.',
        options: [
          'She has already finished her project.',
          'She already finishes her project.',
          'She had finished her project.',
        ],
        correctOptionIndex: 0,
        xpReward: 15,
      },
      {
        id: 'ex-3',
        type: ExerciseType.Reading,
        prompt: 'Read the text and answer.',
        passage:
          'Maria has lived in three different countries. She has learned two new languages and has made friends everywhere she has gone.',
        questions: [
          {
            id: 'ex-3-q1',
            type: ExerciseType.MultipleChoice,
            prompt: 'How many languages has Maria learned?',
            options: ['One', 'Two', 'Three', 'None'],
            correctOptionIndex: 1,
            xpReward: 10,
          },
        ],
        xpReward: 10,
      },
    ],
  },
  {
    id: 'en-b1-conditionals',
    language: 'en',
    level: CefrLevel.B1,
    title: 'First and Second Conditional',
    description: 'Talk about real and hypothetical situations.',
    iconEmoji: '🔀',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 15,
    xpReward: 45,
    order: 8,
    requiresLessonIds: ['en-b1-present-perfect'],
    explanation:
      'First conditional (real/possible future): "If + present simple, will + verb" — "If it rains, I will stay home." Second conditional (hypothetical/unreal): "If + past simple, would + verb" — "If I won the lottery, I would travel the world."',
    examples: [
      'If I have time, I will call you.',
      'If I were you, I would apply for that job.',
      "If she studied more, she would pass the exam.",
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the correct sentence.',
        options: [
          'If I win the lottery, I will travel the world.',
          'If I would win the lottery, I will travel the world.',
          'If I win the lottery, I would travel the world.',
          'If I winning the lottery, I will travel the world.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence (hypothetical).',
        sentenceWithBlank: 'If I ___ more money, I would buy a new car.',
        options: ['have', 'had', 'will have', 'has'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.Translation,
        prompt: 'Translate to English.',
        sourceText: 'Si llueve mañana, me quedaré en casa.',
        acceptedAnswers: [
          'If it rains tomorrow, I will stay home',
          'If it rains tomorrow, I will stay home.',
          "If it rains tomorrow, I'll stay home",
          "If it rains tomorrow, I'll stay home.",
        ],
        xpReward: 15,
      },
    ],
  },
  {
    id: 'en-b1-passive-voice',
    language: 'en',
    level: CefrLevel.B1,
    title: 'Passive Voice',
    description: 'Focus on the action instead of who does it.',
    iconEmoji: '🎯',
    primarySkill: Skill.Grammar,
    estimatedMinutes: 15,
    xpReward: 45,
    order: 9,
    requiresLessonIds: ['en-b1-conditionals'],
    explanation:
      'The passive voice ("be + past participle") is used when the action matters more than who does it. "The report was submitted yesterday" instead of "Someone submitted the report yesterday."',
    examples: [
      'The email was sent this morning.',
      'The new policy will be announced next week.',
      'The building was designed by a famous architect.',
    ],
    vocabulary: [],
    exercises: [
      {
        id: 'ex-1',
        type: ExerciseType.MultipleChoice,
        prompt: 'Choose the passive form of: "They deliver the packages on Fridays."',
        options: [
          'The packages are delivered on Fridays.',
          'The packages deliver on Fridays.',
          'The packages were delivering on Fridays.',
          'The packages delivered on Fridays.',
        ],
        correctOptionIndex: 0,
        xpReward: 10,
      },
      {
        id: 'ex-2',
        type: ExerciseType.FillBlank,
        prompt: 'Complete the sentence in the passive.',
        sentenceWithBlank: 'The report ___ by the end of the day.',
        options: ['will submit', 'will be submitted', 'submitted', 'is submitting'],
        correctOptionIndex: 1,
        xpReward: 10,
      },
      {
        id: 'ex-3',
        type: ExerciseType.TrueFalse,
        prompt: 'True or false?',
        statement: '"The cake was baked by my mother" is an example of the passive voice.',
        correctAnswer: true,
        xpReward: 10,
      },
    ],
  },
];
